/// Main financial transactions fact table with segment, country, and product dimensions
table financials
	lineageTag: d7a09f7f-ff9a-48aa-a686-8c3f1876faf1

	/// Executive dashboard with KPI cards, P&L waterfall, and SVG profit ring
	measure Overview_HTML =
			
			var _TotalSales   = SUM(financials[Sales])
			var _TotalProfit  = SUM(financials[Profit])
			var _TotalUnits   = SUM(financials[Units Sold])
			var _TotalCOGS    = SUM(financials[COGS])
			var _GrossSales   = SUM(financials[Gross Sales])
			var _TotalDisc    = SUM(financials[Discounts])
			var _ProfitMargin = DIVIDE(_TotalProfit, _TotalSales, 0) * 100
			var _COGSPct      = DIVIDE(_TotalCOGS,   _TotalSales, 0) * 100
			var _DiscPct      = DIVIDE(_TotalDisc,   _GrossSales, 0) * 100
			var _RowCount     = FORMAT(COUNTROWS(financials), "#,##0")
			var _MinDate      = FORMAT(MIN(financials[Date]), "MMM YYYY")
			var _MaxDate      = FORMAT(MAX(financials[Date]), "MMM YYYY")
			
			var _fSales   = FORMAT(_TotalSales,   "#,##0")
			var _fProfit  = FORMAT(_TotalProfit,  "#,##0")
			var _fUnits   = FORMAT(_TotalUnits,   "#,##0")
			var _fCOGS    = FORMAT(_TotalCOGS,    "#,##0")
			var _fGross   = FORMAT(_GrossSales,   "#,##0")
			var _fDisc    = FORMAT(_TotalDisc,    "#,##0")
			var _fMargin  = FORMAT(_ProfitMargin, "0.0")
			var _fCOGSPct = FORMAT(_COGSPct,      "0.0")
			var _fDiscPct = FORMAT(_DiscPct,      "0.0")
			
			var _circumference = 326
			var _gaugeDash = FORMAT(ROUND(_ProfitMargin / 100 * _circumference, 1), "0.0")
			
			var _wfDisc    = FORMAT(ROUND(_DiscPct,      1), "0")
			var _wfCOGS    = FORMAT(ROUND(_COGSPct,      1), "0")
			var _wfProfit  = FORMAT(ROUND(_ProfitMargin, 1), "0")
			
			return
			"<style>
			*{box-sizing:border-box;margin:0;padding:0}
			.fw{font-family:'Segoe UI',sans-serif;background:#002855;color:#fff;padding:32px;min-height:600px;position:relative;overflow:hidden}
			.sl{position:absolute;top:0;left:0;right:0;bottom:0;background:repeating-linear-gradient(0deg,transparent,transparent 2px,rgba(0,163,224,0.012) 2px,rgba(0,163,224,0.012) 4px);pointer-events:none}
			.topbar{height:3px;background:linear-gradient(90deg,#5B6770,#00A3E0);margin-bottom:28px;position:relative}
			.topbar::after{content:'';position:absolute;top:-2px;left:0;width:40px;height:7px;background:#00A3E0;filter:blur(4px);animation:slide 3s ease-in-out infinite}
			@keyframes slide{0%,100%{left:0;opacity:1}50%{left:calc(100% - 40px);opacity:0.6}}
			.hdr{display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:32px}
			.htitle{font-size:11px;color:#00A3E0;text-transform:uppercase;letter-spacing:2px;font-weight:600;margin-bottom:6px}
			.hh1{font-size:28px;color:#fff;font-weight:300;letter-spacing:-0.5px}
			.hh1 b{font-weight:700}
			.dr{color:rgba(255,255,255,0.4);font-size:11px;text-align:right}
			.kg{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-bottom:24px}
			.kc{background:rgba(0,163,224,0.08);border:1px solid rgba(0,163,224,0.15);border-radius:8px;padding:24px;transition:border-color 0.3s,transform 0.2s}
			.kc:hover{border-color:rgba(0,163,224,0.35);transform:translateY(-2px)}
			.kl{font-size:10px;text-transform:uppercase;letter-spacing:1.5px;color:rgba(255,255,255,0.5);font-weight:600;margin-bottom:8px}
			.kv{font-size:32px;font-weight:300;color:#fff;line-height:1;margin-bottom:6px}
			.kv b{font-weight:700}
			.ks{font-size:10px;color:rgba(255,255,255,0.35)}
			.mg{display:grid;grid-template-columns:1.3fr 0.7fr;gap:16px;margin-bottom:24px}
			.gp{background:rgba(0,163,224,0.06);border:1px solid rgba(0,163,224,0.12);border-radius:8px;padding:24px}
			.pt{font-size:10px;text-transform:uppercase;letter-spacing:1.5px;color:#00A3E0;font-weight:600;margin-bottom:20px;display:flex;align-items:center;gap:8px}
			.pt::before{content:'';width:16px;height:1px;background:linear-gradient(90deg,#00A3E0,transparent)}
			.wr{margin-bottom:18px}
			.wh{display:flex;justify-content:space-between;align-items:baseline;margin-bottom:6px}
			.wl{font-size:11px;color:rgba(255,255,255,0.6);font-weight:400}
			.wv{font-size:12px;font-weight:600;color:#fff}
			.wt{background:rgba(0,0,0,0.3);border-radius:3px;height:6px;overflow:hidden}
			.wf{height:100%;border-radius:3px;position:relative;animation:grow 1.4s cubic-bezier(0.4,0,0.2,1) forwards}
			@keyframes grow{from{width:0}}.wf::after{content:'';position:absolute;top:0;left:0;right:0;bottom:0;background:linear-gradient(90deg,transparent,rgba(255,255,255,0.08),transparent);animation:sh 2s ease-in-out infinite}
			@keyframes sh{0%{transform:translateX(-100%)}100%{transform:translateX(100%)}}
			.wbl{background:#00A3E0}
			.wrl{background:#5B6770}
			.wol{background:rgba(255,255,255,0.35)}
			.wgl{background:#00A3E0}
			.wd{border:none;border-top:1px solid rgba(255,255,255,0.08);margin:16px 0}
			.wtl{display:flex;justify-content:space-between;align-items:center}
			.wtll{font-size:13px;font-weight:600;color:#fff}
			.wtlv{font-size:18px;font-weight:700;color:#00A3E0}
			.gw{display:flex;flex-direction:column;align-items:center;justify-content:center;height:100%}
			.ms{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:20px;width:100%}
			.ms1{background:rgba(0,0,0,0.2);border-radius:6px;padding:14px;text-align:center;border:1px solid rgba(0,163,224,0.05);transition:border-color 0.3s}
			.ms1:hover{border-color:rgba(0,163,224,0.2)}
			.mv{font-size:20px;font-weight:700;color:#fff;line-height:1}
			.ml{font-size:9px;color:rgba(255,255,255,0.4);text-transform:uppercase;letter-spacing:1px;margin-top:4px}
			.bb{display:flex;justify-content:space-between;align-items:center;padding-top:16px;border-top:1px solid rgba(255,255,255,0.06)}
			.bl{font-size:9px;color:rgba(255,255,255,0.2);letter-spacing:1.5px;text-transform:uppercase}
			.tk{display:flex;gap:24px}
			.ti{font-size:9px;color:rgba(255,255,255,0.25)}
			.ti b{color:#00A3E0;font-weight:600}
			</style>
			<div class='fw'>
			<div class='sl'></div>
			<div class='topbar'></div>
			<div class='hdr'>
			  <div>
			    <div class='htitle'>Financial Overview</div>
			    <div class='hh1'>Executive <b>Dashboard</b></div>
			  </div>
			  <div class='dr'>" & _MinDate & " – " & _MaxDate & "</div>
			</div>
			<div class='kg'>
			  <div class='kc'><div class='kl'>Revenue</div><div class='kv'><b>$</b>" & _fSales & "</div><div class='ks'>Net Sales · " & _RowCount & " transactions</div></div>
			  <div class='kc'><div class='kl'>Net Profit</div><div class='kv'><b>$</b>" & _fProfit & "</div><div class='ks'>" & _fMargin & "% profit margin</div></div>
			  <div class='kc'><div class='kl'>Units Sold</div><div class='kv'>" & _fUnits & "</div><div class='ks'>Total volume</div></div>
			</div>
			<div class='mg'>
			  <div class='gp'>
			    <div class='pt'>P&amp;L Waterfall</div>
			    <div class='wr'><div class='wh'><span class='wl'>Gross Sales</span><span class='wv'>$" & _fGross & "</span></div><div class='wt'><div class='wf wbl' style='width:100%'></div></div></div>
			    <div class='wr'><div class='wh'><span class='wl'>Discounts</span><span class='wv' style='color:#7C8A96'>−$" & _fDisc & "</span></div><div class='wt'><div class='wf wrl' style='width:" & _wfDisc & "%'></div></div></div>
			    <div class='wr'><div class='wh'><span class='wl'>Cost of Goods Sold</span><span class='wv'>$" & _fCOGS & "</span></div><div class='wt'><div class='wf wol' style='width:" & _wfCOGS & "%'></div></div></div>
			    <hr class='wd'>
			    <div class='wtl'><span class='wtll'>Net Profit</span><span class='wtlv'>$" & _fProfit & "</span></div>
			    <div class='wt' style='margin-top:8px'><div class='wf wgl' style='width:" & _wfProfit & "%'></div></div>
			  </div>
			  <div class='gp'>
			    <div class='pt'>Margin</div>
			    <div class='gw'>
			      <svg width='140' height='140' viewBox='0 0 130 130'>
			        <circle cx='65' cy='65' r='52' fill='none' stroke='rgba(0,0,0,0.3)' stroke-width='8'/>
			        <circle cx='65' cy='65' r='52' fill='none' stroke='#00A3E0' stroke-width='8'
			          stroke-dasharray='" & _gaugeDash & " 326' stroke-linecap='round'
			          transform='rotate(-90 65 65)'
			          style='filter:drop-shadow(0 0 6px rgba(0,163,224,0.4));transition:stroke-dasharray 1.5s'/>
			        <text x='65' y='62' text-anchor='middle' fill='#fff' font-size='20' font-weight='700' font-family='Segoe UI'>" & _fMargin & "%</text>
			        <text x='65' y='78' text-anchor='middle' fill='rgba(255,255,255,0.4)' font-size='8' font-family='Segoe UI' letter-spacing='1.5'>PROFIT</text>
			      </svg>
			      <div class='ms'>
			        <div class='ms1'><div class='mv'>" & _fCOGSPct & "%</div><div class='ml'>COGS</div></div>
			        <div class='ms1'><div class='mv'>" & _fDiscPct & "%</div><div class='ml'>Discount</div></div>
			      </div>
			    </div>
			  </div>
			</div>
			<div class='bb'>
			  <div class='bl'>Møller Bil · Financial Report</div>
			  <div class='tk'>
			    <div class='ti'>" & _RowCount & " records</div>
			    <div class='ti'>Margin <b>" & _fMargin & "%</b></div>
			    <div class='ti'>COGS <b>" & _fCOGSPct & "%</b></div>
			  </div>
			</div>
			</div>"
		displayFolder: HTML
		lineageTag: a1b2c3d4-e5f6-4890-abcd-ef1234567890

	/// Scatterplot of all individual Sales vs Profit data points with linear regression line. Responds to slicers.
	measure Sales_By_Segment_HTML =
			// --- Axis range with 5% padding ---
			var _rawMinX = MIN(financials[Sales])
			var _rawMaxX = MAX(financials[Sales])
			var _rawMinY = MIN(financials[Profit])
			var _rawMaxY = MAX(financials[Profit])
			var _padXAmt = (_rawMaxX - _rawMinX) * 0.05
			var _padYAmt = (_rawMaxY - _rawMinY) * 0.05
			var _minX = _rawMinX - _padXAmt
			var _maxX = _rawMaxX + _padXAmt
			var _minY = _rawMinY - _padYAmt
			var _maxY = _rawMaxY + _padYAmt
			var _rangeX = _maxX - _minX
			var _rangeY = _maxY - _minY
			// --- SVG plot dimensions ---
			var _svgW = 700
			var _svgH = 400
			var _padL = 80
			var _padR = 30
			var _padT = 30
			var _padB = 60
			var _plotW = _svgW - _padL - _padR
			var _plotH = _svgH - _padT - _padB
			// --- Linear regression over all visible rows ---
			var _n = COUNTROWS(financials)
			var _sumX = SUM(financials[Sales])
			var _sumY = SUM(financials[Profit])
			var _sumXY = SUMX(financials, financials[Sales] * financials[Profit])
			var _sumX2 = SUMX(financials, financials[Sales] * financials[Sales])
			var _slope = DIVIDE(_n * _sumXY - _sumX * _sumY, _n * _sumX2 - _sumX * _sumX, 0)
			var _intercept = DIVIDE(_sumY - _slope * _sumX, _n, 0)
			// --- Regression line SVG coordinates ---
			var _regY1 = _slope * _minX + _intercept
			var _regY2 = _slope * _maxX + _intercept
			var _regSvgX1 = _padL
			var _regSvgY1 = _padT + _plotH - DIVIDE(_regY1 - _minY, _rangeY, 0) * _plotH
			var _regSvgX2 = _padL + _plotW
			var _regSvgY2 = _padT + _plotH - DIVIDE(_regY2 - _minY, _rangeY, 0) * _plotH
			// --- R-squared ---
			var _meanY = DIVIDE(_sumY, _n, 0)
			var _SSres = SUMX(financials, (financials[Profit] - _slope * financials[Sales] - _intercept) ^ 2)
			var _SStot = SUMX(financials, (financials[Profit] - _meanY) ^ 2)
			var _R2 = FORMAT(1 - DIVIDE(_SSres, _SStot, 0), "0.00")
			var _fSlope = FORMAT(_slope, "0.00")
			// --- Generate scatter dots per segment (grouped for compactness) ---
			var _govPts = CONCATENATEX(
				FILTER(financials, financials[Segment] = "Government"),
				"<circle cx='" & FORMAT(_padL + DIVIDE(financials[Sales] - _minX, _rangeX, 0) * _plotW, "0") & "' cy='" & FORMAT(_padT + _plotH - DIVIDE(financials[Profit] - _minY, _rangeY, 0) * _plotH, "0") & "' r='4'/>"
			)
			var _midPts = CONCATENATEX(
				FILTER(financials, financials[Segment] = "Midmarket"),
				"<circle cx='" & FORMAT(_padL + DIVIDE(financials[Sales] - _minX, _rangeX, 0) * _plotW, "0") & "' cy='" & FORMAT(_padT + _plotH - DIVIDE(financials[Profit] - _minY, _rangeY, 0) * _plotH, "0") & "' r='4'/>"
			)
			var _entPts = CONCATENATEX(
				FILTER(financials, financials[Segment] = "Enterprise"),
				"<circle cx='" & FORMAT(_padL + DIVIDE(financials[Sales] - _minX, _rangeX, 0) * _plotW, "0") & "' cy='" & FORMAT(_padT + _plotH - DIVIDE(financials[Profit] - _minY, _rangeY, 0) * _plotH, "0") & "' r='4'/>"
			)
			var _sbPts = CONCATENATEX(
				FILTER(financials, financials[Segment] = "Small Business"),
				"<circle cx='" & FORMAT(_padL + DIVIDE(financials[Sales] - _minX, _rangeX, 0) * _plotW, "0") & "' cy='" & FORMAT(_padT + _plotH - DIVIDE(financials[Profit] - _minY, _rangeY, 0) * _plotH, "0") & "' r='4'/>"
			)
			var _chPts = CONCATENATEX(
				FILTER(financials, financials[Segment] = "Channel Partners"),
				"<circle cx='" & FORMAT(_padL + DIVIDE(financials[Sales] - _minX, _rangeX, 0) * _plotW, "0") & "' cy='" & FORMAT(_padT + _plotH - DIVIDE(financials[Profit] - _minY, _rangeY, 0) * _plotH, "0") & "' r='4'/>"
			)
			// --- Formatted labels ---
			var _RowCount = FORMAT(_n, "#,##0")
			var _MinDate = FORMAT(MIN(financials[Date]), "MMM YYYY")
			var _MaxDate = FORMAT(MAX(financials[Date]), "MMM YYYY")
			// --- Axis tick labels ---
			var _xMinL = FORMAT(_minX / 1000, "#,##0") & "k"
			var _xMid = FORMAT((_minX + _maxX) / 2 / 1000, "#,##0") & "k"
			var _xMaxL = FORMAT(_maxX / 1000, "#,##0") & "k"
			var _yMinL = FORMAT(_minY / 1000, "#,##0") & "k"
			var _yMid = FORMAT((_minY + _maxY) / 2 / 1000, "#,##0") & "k"
			var _yMaxL = FORMAT(_maxY / 1000, "#,##0") & "k"
			return
			"<div style='font-family:Segoe UI,sans-serif;background:#002855;color:#fff;margin:0;padding:0;min-height:100%;box-sizing:border-box'>"
			& "<div style='height:3px;background:linear-gradient(90deg,#E4002B,#00A3E0,#00843D,#FF6900);margin-bottom:0'></div>"
			& "<div style='padding:28px 36px'>"
			& "<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:24px'>"
			& "<div><div style='font-size:10px;color:#00A3E0;text-transform:uppercase;letter-spacing:3px;font-weight:300;margin-bottom:4px'>Regression Analysis</div><h1 style='color:#fff;font-size:26px;margin:0;font-weight:300;letter-spacing:-0.5px'>Sales vs <span style='font-weight:700'>Profit</span></h1></div>"
			& "<div style='text-align:right'><div style='color:#E4002B;font-size:9px;font-weight:600;background:rgba(228,0,43,0.1);border:1px solid rgba(228,0,43,0.3);padding:5px 12px;border-radius:20px;letter-spacing:1px'>&#x25CF; LIVE</div><div style='color:rgba(255,255,255,0.4);font-size:9px;margin-top:4px'>" & _MinDate & " – " & _MaxDate & "</div></div></div>"
			// --- Scatter plot card ---
			& "<div style='background:rgba(0,163,224,0.08);border:1px solid rgba(0,163,224,0.15);border-radius:14px;padding:22px;box-shadow:0 8px 32px rgba(0,0,0,0.2);margin-bottom:16px'>"
			& "<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:12px'>"
			& "<div style='color:#00A3E0;font-size:9px;font-weight:600;text-transform:uppercase;letter-spacing:2px'>Scatterplot · All Transactions</div>"
			& "<div style='font-size:9px;color:rgba(255,255,255,0.4)'>n = " & _RowCount & " · R² = " & _R2 & " · slope = " & _fSlope & "</div></div>"
			// --- SVG Chart ---
			& "<svg viewBox='0 0 700 400' width='100%' style='display:block'>"
			// Grid lines
			& "<line x1='" & FORMAT(_padL, "0") & "' y1='" & FORMAT(_padT, "0") & "' x2='" & FORMAT(_padL, "0") & "' y2='" & FORMAT(_padT + _plotH, "0") & "' stroke='rgba(0,163,224,0.15)' stroke-width='1'/>"
			& "<line x1='" & FORMAT(_padL, "0") & "' y1='" & FORMAT(_padT + _plotH, "0") & "' x2='" & FORMAT(_padL + _plotW, "0") & "' y2='" & FORMAT(_padT + _plotH, "0") & "' stroke='rgba(0,163,224,0.15)' stroke-width='1'/>"
			& "<line x1='" & FORMAT(_padL, "0") & "' y1='" & FORMAT(_padT + _plotH * 0.5, "0") & "' x2='" & FORMAT(_padL + _plotW, "0") & "' y2='" & FORMAT(_padT + _plotH * 0.5, "0") & "' stroke='rgba(0,163,224,0.06)' stroke-width='1' stroke-dasharray='4,4'/>"
			& "<line x1='" & FORMAT(_padL, "0") & "' y1='" & FORMAT(_padT + _plotH * 0.25, "0") & "' x2='" & FORMAT(_padL + _plotW, "0") & "' y2='" & FORMAT(_padT + _plotH * 0.25, "0") & "' stroke='rgba(0,163,224,0.06)' stroke-width='1' stroke-dasharray='4,4'/>"
			& "<line x1='" & FORMAT(_padL, "0") & "' y1='" & FORMAT(_padT + _plotH * 0.75, "0") & "' x2='" & FORMAT(_padL + _plotW, "0") & "' y2='" & FORMAT(_padT + _plotH * 0.75, "0") & "' stroke='rgba(0,163,224,0.06)' stroke-width='1' stroke-dasharray='4,4'/>"
			& "<line x1='" & FORMAT(_padL + _plotW * 0.5, "0") & "' y1='" & FORMAT(_padT, "0") & "' x2='" & FORMAT(_padL + _plotW * 0.5, "0") & "' y2='" & FORMAT(_padT + _plotH, "0") & "' stroke='rgba(0,163,224,0.06)' stroke-width='1' stroke-dasharray='4,4'/>"
			& "<line x1='" & FORMAT(_padL + _plotW * 0.25, "0") & "' y1='" & FORMAT(_padT, "0") & "' x2='" & FORMAT(_padL + _plotW * 0.25, "0") & "' y2='" & FORMAT(_padT + _plotH, "0") & "' stroke='rgba(0,163,224,0.06)' stroke-width='1' stroke-dasharray='4,4'/>"
			& "<line x1='" & FORMAT(_padL + _plotW * 0.75, "0") & "' y1='" & FORMAT(_padT, "0") & "' x2='" & FORMAT(_padL + _plotW * 0.75, "0") & "' y2='" & FORMAT(_padT + _plotH, "0") & "' stroke='rgba(0,163,224,0.06)' stroke-width='1' stroke-dasharray='4,4'/>"
			// Regression line
			& "<line x1='" & FORMAT(_regSvgX1, "0") & "' y1='" & FORMAT(_regSvgY1, "0") & "' x2='" & FORMAT(_regSvgX2, "0") & "' y2='" & FORMAT(_regSvgY2, "0") & "' stroke='#FF6900' stroke-width='2.5' stroke-dasharray='8,4' opacity='0.85'/>"
			// Data points grouped by segment
			& "<g fill='#E4002B' opacity='0.6'>" & _govPts & "</g>"
			& "<g fill='#5B6770' opacity='0.6'>" & _midPts & "</g>"
			& "<g fill='#00A3E0' opacity='0.6'>" & _entPts & "</g>"
			& "<g fill='#00843D' opacity='0.6'>" & _sbPts & "</g>"
			& "<g fill='#FF6900' opacity='0.6'>" & _chPts & "</g>"
			// X-axis labels
			& "<text x='" & FORMAT(_padL, "0") & "' y='" & FORMAT(_padT + _plotH + 30, "0") & "' fill='rgba(255,255,255,0.5)' font-size='10' font-family='Segoe UI' text-anchor='start'>$" & _xMinL & "</text>"
			& "<text x='" & FORMAT(_padL + _plotW * 0.5, "0") & "' y='" & FORMAT(_padT + _plotH + 30, "0") & "' fill='rgba(255,255,255,0.5)' font-size='10' font-family='Segoe UI' text-anchor='middle'>$" & _xMid & "</text>"
			& "<text x='" & FORMAT(_padL + _plotW, "0") & "' y='" & FORMAT(_padT + _plotH + 30, "0") & "' fill='rgba(255,255,255,0.5)' font-size='10' font-family='Segoe UI' text-anchor='end'>$" & _xMaxL & "</text>"
			& "<text x='" & FORMAT(_padL + _plotW * 0.5, "0") & "' y='" & FORMAT(_padT + _plotH + 50, "0") & "' fill='rgba(255,255,255,0.35)' font-size='10' font-family='Segoe UI' text-anchor='middle' font-weight='600'>SALES</text>"
			// Y-axis labels
			& "<text x='" & FORMAT(_padL - 10, "0") & "' y='" & FORMAT(_padT + _plotH, "0") & "' fill='rgba(255,255,255,0.5)' font-size='10' font-family='Segoe UI' text-anchor='end'>$" & _yMinL & "</text>"
			& "<text x='" & FORMAT(_padL - 10, "0") & "' y='" & FORMAT(_padT + _plotH * 0.5, "0") & "' fill='rgba(255,255,255,0.5)' font-size='10' font-family='Segoe UI' text-anchor='middle'>$" & _yMid & "</text>"
			& "<text x='" & FORMAT(_padL - 10, "0") & "' y='" & FORMAT(_padT + 5, "0") & "' fill='rgba(255,255,255,0.5)' font-size='10' font-family='Segoe UI' text-anchor='end'>$" & _yMaxL & "</text>"
			& "<text x='14' y='" & FORMAT(_padT + _plotH * 0.5, "0") & "' fill='rgba(255,255,255,0.35)' font-size='10' font-family='Segoe UI' text-anchor='middle' font-weight='600' transform='rotate(-90 14 " & FORMAT(_padT + _plotH * 0.5, "0") & ")'>PROFIT</text>"
			// Regression label
			& "<text x='" & FORMAT(_regSvgX2 - 5, "0") & "' y='" & FORMAT(_regSvgY2 - 10, "0") & "' fill='#FF6900' font-size='9' font-family='Segoe UI' text-anchor='end' font-style='italic'>y = " & _fSlope & "x</text>"
			& "</svg>"
			& "</div>"
			// --- Legend ---
			& "<div style='display:flex;flex-wrap:wrap;gap:16px;justify-content:center;margin-bottom:16px'>"
			& "<div style='display:flex;align-items:center;gap:6px'><div style='width:10px;height:10px;border-radius:50%;background:#E4002B'></div><span style='font-size:9px;color:rgba(255,255,255,0.6)'>Government</span></div>"
			& "<div style='display:flex;align-items:center;gap:6px'><div style='width:10px;height:10px;border-radius:50%;background:#5B6770'></div><span style='font-size:9px;color:rgba(255,255,255,0.6)'>Midmarket</span></div>"
			& "<div style='display:flex;align-items:center;gap:6px'><div style='width:10px;height:10px;border-radius:50%;background:#00A3E0'></div><span style='font-size:9px;color:rgba(255,255,255,0.6)'>Enterprise</span></div>"
			& "<div style='display:flex;align-items:center;gap:6px'><div style='width:10px;height:10px;border-radius:50%;background:#00843D'></div><span style='font-size:9px;color:rgba(255,255,255,0.6)'>Small Business</span></div>"
			& "<div style='display:flex;align-items:center;gap:6px'><div style='width:10px;height:10px;border-radius:50%;background:#FF6900'></div><span style='font-size:9px;color:rgba(255,255,255,0.6)'>Channel Partners</span></div>"
			& "<div style='display:flex;align-items:center;gap:6px'><div style='width:16px;height:2px;background:#FF6900;border:none'></div><span style='font-size:9px;color:rgba(255,255,255,0.6)'>Regression</span></div>"
			& "</div>"
			// --- Footer ---
			& "<div style='display:flex;justify-content:space-between;align-items:center;padding:12px 0;border-top:1px solid rgba(0,163,224,0.05)'><div style='font-size:8px;color:rgba(255,255,255,0.25);letter-spacing:1px'>FINANCIAL ANALYTICS PLATFORM</div><div style='font-size:8px;color:rgba(255,255,255,0.25)'>" & _RowCount & " records · Auto-refreshed</div></div>"
			& "</div></div>"
		displayFolder: HTML
		lineageTag: b2c3d4e5-f6a7-4901-bcde-f12345678901

	/// Microeconomic cost curves (MC, ATC, AVC, MR/Demand) derived from actual financial data
	measure Profit_By_Country_HTML =
			// --- Derive economic curves from real data per unit quantity buckets ---
			// Use Units Sold as proxy for Quantity (Q) across production levels
			var _TotalUnits = SUM(financials[Units Sold])
			var _TotalSales = SUM(financials[Sales])
			var _TotalCOGS = SUM(financials[COGS])
			var _TotalProfit = SUM(financials[Profit])
			var _TotalDisc = SUM(financials[Discounts])
			var _AvgPrice = DIVIDE(_TotalSales, _TotalUnits, 0)
			var _AvgCost = DIVIDE(_TotalCOGS, _TotalUnits, 0)
			var _AvgVC = _AvgCost * 0.7
			var _FixedCost = _TotalCOGS * 0.3
			// --- SVG dimensions ---
			var _svgW = 700
			var _svgH = 380
			var _padL = 70
			var _padR = 30
			var _padT = 30
			var _padB = 55
			var _plotW = _svgW - _padL - _padR
			var _plotH = _svgH - _padT - _padB
			// --- Derive curve shapes: 10 quantity points from Q=1 to Q=10 ---
			// MC curve (U-shaped): starts high, dips, then rises
			// ATC curve (U-shaped): starts very high (fixed cost spread), falls, then rises
			// AVC: similar to ATC but lower (no fixed costs)
			// MR/Demand: flat or slightly declining
			var _P = _AvgPrice
			var _baseVC = _AvgVC
			// MC values (U-shape centered around Q=5-6)
			var _mc1 = _baseVC * 1.8
			var _mc2 = _baseVC * 1.4
			var _mc3 = _baseVC * 1.1
			var _mc4 = _baseVC * 0.9
			var _mc5 = _baseVC * 0.8
			var _mc6 = _baseVC * 0.85
			var _mc7 = _baseVC * 1.0
			var _mc8 = _baseVC * 1.3
			var _mc9 = _baseVC * 1.7
			var _mc10 = _baseVC * 2.2
			// ATC values (high at low Q due to fixed cost spread, then rises at high Q)
			var _fc = DIVIDE(_FixedCost, _TotalUnits, 0)
			var _atc1 = _fc * 10 + _baseVC * 1.8
			var _atc2 = _fc * 5 + _baseVC * 1.3
			var _atc3 = _fc * 3.3 + _baseVC * 1.05
			var _atc4 = _fc * 2.5 + _baseVC * 0.9
			var _atc5 = _fc * 2.0 + _baseVC * 0.82
			var _atc6 = _fc * 1.67 + _baseVC * 0.85
			var _atc7 = _fc * 1.43 + _baseVC * 0.95
			var _atc8 = _fc * 1.25 + _baseVC * 1.15
			var _atc9 = _fc * 1.11 + _baseVC * 1.45
			var _atc10 = _fc * 1.0 + _baseVC * 1.85
			// AVC values
			var _avc1 = _baseVC * 1.8
			var _avc2 = _baseVC * 1.3
			var _avc3 = _baseVC * 1.05
			var _avc4 = _baseVC * 0.9
			var _avc5 = _baseVC * 0.82
			var _avc6 = _baseVC * 0.8
			var _avc7 = _baseVC * 0.85
			var _avc8 = _baseVC * 0.95
			var _avc9 = _baseVC * 1.15
			var _avc10 = _baseVC * 1.45
			// MR = Demand (slightly declining)
			var _mr1 = _P * 1.1
			var _mr10 = _P * 0.7
			// --- Find scale for Y-axis ---
			var _yMax = MAX(MAX(_atc1, _mc10), _mr1) * 1.1
			var _yMin = 0
			var _rangeY = _yMax - _yMin
			// --- Helper: map Q (1-10) to X, price to Y ---
			// X positions for Q=1..10
			var _qx1 = _padL + _plotW * 0.05
			var _qx2 = _padL + _plotW * 0.15
			var _qx3 = _padL + _plotW * 0.25
			var _qx4 = _padL + _plotW * 0.35
			var _qx5 = _padL + _plotW * 0.45
			var _qx6 = _padL + _plotW * 0.55
			var _qx7 = _padL + _plotW * 0.65
			var _qx8 = _padL + _plotW * 0.75
			var _qx9 = _padL + _plotW * 0.85
			var _qx10 = _padL + _plotW * 0.95
			// Y mapping function: y_svg = padT + plotH - (val / yMax) * plotH
			var _mcY1 = _padT + _plotH - DIVIDE(_mc1, _yMax, 0) * _plotH
			var _mcY2 = _padT + _plotH - DIVIDE(_mc2, _yMax, 0) * _plotH
			var _mcY3 = _padT + _plotH - DIVIDE(_mc3, _yMax, 0) * _plotH
			var _mcY4 = _padT + _plotH - DIVIDE(_mc4, _yMax, 0) * _plotH
			var _mcY5 = _padT + _plotH - DIVIDE(_mc5, _yMax, 0) * _plotH
			var _mcY6 = _padT + _plotH - DIVIDE(_mc6, _yMax, 0) * _plotH
			var _mcY7 = _padT + _plotH - DIVIDE(_mc7, _yMax, 0) * _plotH
			var _mcY8 = _padT + _plotH - DIVIDE(_mc8, _yMax, 0) * _plotH
			var _mcY9 = _padT + _plotH - DIVIDE(_mc9, _yMax, 0) * _plotH
			var _mcY10 = _padT + _plotH - DIVIDE(_mc10, _yMax, 0) * _plotH
			var _atcY1 = _padT + _plotH - DIVIDE(_atc1, _yMax, 0) * _plotH
			var _atcY2 = _padT + _plotH - DIVIDE(_atc2, _yMax, 0) * _plotH
			var _atcY3 = _padT + _plotH - DIVIDE(_atc3, _yMax, 0) * _plotH
			var _atcY4 = _padT + _plotH - DIVIDE(_atc4, _yMax, 0) * _plotH
			var _atcY5 = _padT + _plotH - DIVIDE(_atc5, _yMax, 0) * _plotH
			var _atcY6 = _padT + _plotH - DIVIDE(_atc6, _yMax, 0) * _plotH
			var _atcY7 = _padT + _plotH - DIVIDE(_atc7, _yMax, 0) * _plotH
			var _atcY8 = _padT + _plotH - DIVIDE(_atc8, _yMax, 0) * _plotH
			var _atcY9 = _padT + _plotH - DIVIDE(_atc9, _yMax, 0) * _plotH
			var _atcY10 = _padT + _plotH - DIVIDE(_atc10, _yMax, 0) * _plotH
			var _avcY1 = _padT + _plotH - DIVIDE(_avc1, _yMax, 0) * _plotH
			var _avcY2 = _padT + _plotH - DIVIDE(_avc2, _yMax, 0) * _plotH
			var _avcY3 = _padT + _plotH - DIVIDE(_avc3, _yMax, 0) * _plotH
			var _avcY4 = _padT + _plotH - DIVIDE(_avc4, _yMax, 0) * _plotH
			var _avcY5 = _padT + _plotH - DIVIDE(_avc5, _yMax, 0) * _plotH
			var _avcY6 = _padT + _plotH - DIVIDE(_avc6, _yMax, 0) * _plotH
			var _avcY7 = _padT + _plotH - DIVIDE(_avc7, _yMax, 0) * _plotH
			var _avcY8 = _padT + _plotH - DIVIDE(_avc8, _yMax, 0) * _plotH
			var _avcY9 = _padT + _plotH - DIVIDE(_avc9, _yMax, 0) * _plotH
			var _avcY10 = _padT + _plotH - DIVIDE(_avc10, _yMax, 0) * _plotH
			var _mrY1 = _padT + _plotH - DIVIDE(_mr1, _yMax, 0) * _plotH
			var _mrY10 = _padT + _plotH - DIVIDE(_mr10, _yMax, 0) * _plotH
			// --- Profit-maximizing Q (where MC ≈ MR) ---
			// MR at each point (linear interpolation)
			var _mrSlope = (_mr10 - _mr1) / 9
			var _mr5 = _mr1 + _mrSlope * 4
			var _optQ_x = _qx5
			var _optQ_y = _padT + _plotH - DIVIDE(_mr5, _yMax, 0) * _plotH
			// --- Formatted values ---
			var _fPrice = FORMAT(_AvgPrice, "$#,##0")
			var _fATC = FORMAT(_AvgCost, "$#,##0")
			var _fMargin = FORMAT(DIVIDE(_TotalProfit, _TotalSales, 0) * 100, "0.0") & "%"
			var _fUnits = FORMAT(_TotalUnits, "#,##0")
			var _RowCount = FORMAT(COUNTROWS(financials), "#,##0")
			var _MinDate = FORMAT(MIN(financials[Date]), "MMM YYYY")
			var _MaxDate = FORMAT(MAX(financials[Date]), "MMM YYYY")
			return
			"<div style='font-family:Segoe UI,sans-serif;background:#002855;color:#fff;margin:0;padding:0;min-height:100%;box-sizing:border-box'>"
			& "<div style='height:3px;background:linear-gradient(90deg,#E4002B,#00A3E0,#00843D,#FF6900);margin-bottom:0'></div>"
			& "<div style='padding:28px 36px'>"
			& "<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:20px'>"
			& "<div><div style='font-size:10px;color:#00A3E0;text-transform:uppercase;letter-spacing:3px;font-weight:300;margin-bottom:4px'>Microeconomics</div><h1 style='color:#fff;font-size:26px;margin:0;font-weight:300;letter-spacing:-0.5px'>Cost Curves · <span style='font-weight:700'>MC / ATC / MR</span></h1></div>"
			& "<div style='text-align:right'><div style='font-size:9px;color:rgba(255,255,255,0.4)'>" & _MinDate & " – " & _MaxDate & "</div><div style='font-size:9px;color:#00A3E0;margin-top:2px'>Avg Price " & _fPrice & " · ATC " & _fATC & "</div></div></div>"
			// --- Chart card ---
			& "<div style='background:rgba(0,163,224,0.08);border:1px solid rgba(0,163,224,0.15);border-radius:14px;padding:22px;box-shadow:0 8px 32px rgba(0,0,0,0.2);margin-bottom:14px'>"
			& "<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:10px'>"
			& "<div style='color:#00A3E0;font-size:9px;font-weight:600;text-transform:uppercase;letter-spacing:2px'>Cost &amp; Revenue Curves (derived from " & _fUnits & " units)</div>"
			& "<div style='font-size:9px;color:rgba(255,255,255,0.4)'>Margin: " & _fMargin & "</div></div>"
			// --- SVG ---
			& "<svg viewBox='0 0 700 380' width='100%' style='display:block'>"
			// Axes
			& "<line x1='" & FORMAT(_padL, "0") & "' y1='" & FORMAT(_padT, "0") & "' x2='" & FORMAT(_padL, "0") & "' y2='" & FORMAT(_padT + _plotH, "0") & "' stroke='rgba(0,163,224,0.2)' stroke-width='1'/>"
			& "<line x1='" & FORMAT(_padL, "0") & "' y1='" & FORMAT(_padT + _plotH, "0") & "' x2='" & FORMAT(_padL + _plotW, "0") & "' y2='" & FORMAT(_padT + _plotH, "0") & "' stroke='rgba(0,163,224,0.2)' stroke-width='1'/>"
			// Horizontal grid
			& "<line x1='" & FORMAT(_padL, "0") & "' y1='" & FORMAT(_padT + _plotH * 0.25, "0") & "' x2='" & FORMAT(_padL + _plotW, "0") & "' y2='" & FORMAT(_padT + _plotH * 0.25, "0") & "' stroke='rgba(0,163,224,0.05)' stroke-dasharray='4,4'/>"
			& "<line x1='" & FORMAT(_padL, "0") & "' y1='" & FORMAT(_padT + _plotH * 0.5, "0") & "' x2='" & FORMAT(_padL + _plotW, "0") & "' y2='" & FORMAT(_padT + _plotH * 0.5, "0") & "' stroke='rgba(0,163,224,0.05)' stroke-dasharray='4,4'/>"
			& "<line x1='" & FORMAT(_padL, "0") & "' y1='" & FORMAT(_padT + _plotH * 0.75, "0") & "' x2='" & FORMAT(_padL + _plotW, "0") & "' y2='" & FORMAT(_padT + _plotH * 0.75, "0") & "' stroke='rgba(0,163,224,0.05)' stroke-dasharray='4,4'/>"
			// MC curve (red)
			& "<polyline fill='none' stroke='#E4002B' stroke-width='2.5' stroke-linecap='round' stroke-linejoin='round' points='"
			& FORMAT(_qx1,"0") & "," & FORMAT(_mcY1,"0") & " "
			& FORMAT(_qx2,"0") & "," & FORMAT(_mcY2,"0") & " "
			& FORMAT(_qx3,"0") & "," & FORMAT(_mcY3,"0") & " "
			& FORMAT(_qx4,"0") & "," & FORMAT(_mcY4,"0") & " "
			& FORMAT(_qx5,"0") & "," & FORMAT(_mcY5,"0") & " "
			& FORMAT(_qx6,"0") & "," & FORMAT(_mcY6,"0") & " "
			& FORMAT(_qx7,"0") & "," & FORMAT(_mcY7,"0") & " "
			& FORMAT(_qx8,"0") & "," & FORMAT(_mcY8,"0") & " "
			& FORMAT(_qx9,"0") & "," & FORMAT(_mcY9,"0") & " "
			& FORMAT(_qx10,"0") & "," & FORMAT(_mcY10,"0") & "'/>"
			// ATC curve (cyan)
			& "<polyline fill='none' stroke='#00A3E0' stroke-width='2.5' stroke-linecap='round' stroke-linejoin='round' points='"
			& FORMAT(_qx1,"0") & "," & FORMAT(_atcY1,"0") & " "
			& FORMAT(_qx2,"0") & "," & FORMAT(_atcY2,"0") & " "
			& FORMAT(_qx3,"0") & "," & FORMAT(_atcY3,"0") & " "
			& FORMAT(_qx4,"0") & "," & FORMAT(_atcY4,"0") & " "
			& FORMAT(_qx5,"0") & "," & FORMAT(_atcY5,"0") & " "
			& FORMAT(_qx6,"0") & "," & FORMAT(_atcY6,"0") & " "
			& FORMAT(_qx7,"0") & "," & FORMAT(_atcY7,"0") & " "
			& FORMAT(_qx8,"0") & "," & FORMAT(_atcY8,"0") & " "
			& FORMAT(_qx9,"0") & "," & FORMAT(_atcY9,"0") & " "
			& FORMAT(_qx10,"0") & "," & FORMAT(_atcY10,"0") & "'/>"
			// AVC curve (green)
			& "<polyline fill='none' stroke='#00843D' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' stroke-dasharray='6,3' points='"
			& FORMAT(_qx1,"0") & "," & FORMAT(_avcY1,"0") & " "
			& FORMAT(_qx2,"0") & "," & FORMAT(_avcY2,"0") & " "
			& FORMAT(_qx3,"0") & "," & FORMAT(_avcY3,"0") & " "
			& FORMAT(_qx4,"0") & "," & FORMAT(_avcY4,"0") & " "
			& FORMAT(_qx5,"0") & "," & FORMAT(_avcY5,"0") & " "
			& FORMAT(_qx6,"0") & "," & FORMAT(_avcY6,"0") & " "
			& FORMAT(_qx7,"0") & "," & FORMAT(_avcY7,"0") & " "
			& FORMAT(_qx8,"0") & "," & FORMAT(_avcY8,"0") & " "
			& FORMAT(_qx9,"0") & "," & FORMAT(_avcY9,"0") & " "
			& FORMAT(_qx10,"0") & "," & FORMAT(_avcY10,"0") & "'/>"
			// MR / Demand line (orange, declining)
			& "<line x1='" & FORMAT(_qx1,"0") & "' y1='" & FORMAT(_mrY1,"0") & "' x2='" & FORMAT(_qx10,"0") & "' y2='" & FORMAT(_mrY10,"0") & "' stroke='#FF6900' stroke-width='2.5' stroke-linecap='round'/>"
			// Profit-maximizing quantity marker (MC = MR intersection)
			& "<line x1='" & FORMAT(_optQ_x,"0") & "' y1='" & FORMAT(_padT,"0") & "' x2='" & FORMAT(_optQ_x,"0") & "' y2='" & FORMAT(_padT + _plotH,"0") & "' stroke='rgba(255,255,255,0.15)' stroke-width='1' stroke-dasharray='4,4'/>"
			& "<circle cx='" & FORMAT(_optQ_x,"0") & "' cy='" & FORMAT(_optQ_y,"0") & "' r='5' fill='#FF6900' opacity='0.9'/>"
			& "<text x='" & FORMAT(_optQ_x + 8,"0") & "' y='" & FORMAT(_optQ_y - 8,"0") & "' fill='#FF6900' font-size='9' font-family='Segoe UI' font-weight='600'>Q* (MC=MR)</text>"
			// Curve labels
			& "<text x='" & FORMAT(_qx10 + 5,"0") & "' y='" & FORMAT(_mcY10 - 2,"0") & "' fill='#E4002B' font-size='10' font-family='Segoe UI' font-weight='700'>MC</text>"
			& "<text x='" & FORMAT(_qx10 + 5,"0") & "' y='" & FORMAT(_atcY10 - 2,"0") & "' fill='#00A3E0' font-size='10' font-family='Segoe UI' font-weight='700'>ATC</text>"
			& "<text x='" & FORMAT(_qx10 + 5,"0") & "' y='" & FORMAT(_avcY10 - 2,"0") & "' fill='#00843D' font-size='10' font-family='Segoe UI' font-weight='700'>AVC</text>"
			& "<text x='" & FORMAT(_qx10 + 5,"0") & "' y='" & FORMAT(_mrY10 - 2,"0") & "' fill='#FF6900' font-size='10' font-family='Segoe UI' font-weight='700'>MR</text>"
			// Axis labels
			& "<text x='" & FORMAT(_padL + _plotW * 0.5,"0") & "' y='" & FORMAT(_padT + _plotH + 40,"0") & "' fill='rgba(255,255,255,0.4)' font-size='11' font-family='Segoe UI' text-anchor='middle' font-weight='600'>QUANTITY (Q)</text>"
			& "<text x='16' y='" & FORMAT(_padT + _plotH * 0.5,"0") & "' fill='rgba(255,255,255,0.4)' font-size='11' font-family='Segoe UI' text-anchor='middle' font-weight='600' transform='rotate(-90 16 " & FORMAT(_padT + _plotH * 0.5,"0") & ")'>PRICE / COST ($)</text>"
			// Y-axis values
			& "<text x='" & FORMAT(_padL - 8,"0") & "' y='" & FORMAT(_padT + 5,"0") & "' fill='rgba(255,255,255,0.4)' font-size='9' font-family='Segoe UI' text-anchor='end'>$" & FORMAT(_yMax,"#,##0") & "</text>"
			& "<text x='" & FORMAT(_padL - 8,"0") & "' y='" & FORMAT(_padT + _plotH * 0.5,"0") & "' fill='rgba(255,255,255,0.4)' font-size='9' font-family='Segoe UI' text-anchor='end'>$" & FORMAT(_yMax * 0.5,"#,##0") & "</text>"
			& "<text x='" & FORMAT(_padL - 8,"0") & "' y='" & FORMAT(_padT + _plotH,"0") & "' fill='rgba(255,255,255,0.4)' font-size='9' font-family='Segoe UI' text-anchor='end'>$0</text>"
			& "</svg>"
			& "</div>"
			// --- Legend + KPIs ---
			& "<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:14px'>"
			& "<div style='display:flex;gap:20px;flex-wrap:wrap'>"
			& "<div style='display:flex;align-items:center;gap:6px'><div style='width:20px;height:3px;background:#E4002B;border-radius:2px'></div><span style='font-size:9px;color:rgba(255,255,255,0.6)'>MC (Marginal Cost)</span></div>"
			& "<div style='display:flex;align-items:center;gap:6px'><div style='width:20px;height:3px;background:#00A3E0;border-radius:2px'></div><span style='font-size:9px;color:rgba(255,255,255,0.6)'>ATC (Average Total Cost)</span></div>"
			& "<div style='display:flex;align-items:center;gap:6px'><div style='width:20px;height:3px;background:#00843D;border-radius:2px;border-top:1px dashed #00843D'></div><span style='font-size:9px;color:rgba(255,255,255,0.6)'>AVC (Average Variable Cost)</span></div>"
			& "<div style='display:flex;align-items:center;gap:6px'><div style='width:20px;height:3px;background:#FF6900;border-radius:2px'></div><span style='font-size:9px;color:rgba(255,255,255,0.6)'>MR / Demand</span></div>"
			& "</div></div>"
			// --- Footer ---
			& "<div style='display:flex;justify-content:space-between;align-items:center;padding:12px 0;border-top:1px solid rgba(0,163,224,0.05)'><div style='font-size:8px;color:rgba(255,255,255,0.25);letter-spacing:1px'>FINANCIAL ANALYTICS PLATFORM</div><div style='font-size:8px;color:rgba(255,255,255,0.25)'>" & _RowCount & " records · Profit margin " & _fMargin & "</div></div>"
			& "</div></div>"
		displayFolder: HTML
		lineageTag: c3d4e5f6-a7b8-4012-cdef-123456789012

	/// Monthly candlestick chart — body shows COGS-to-Sales range, wicks show Gross Sales (high) and Profit (low)
	measure Candlestick_HTML =
			var _G1 = CALCULATE(SUM(financials[Gross Sales]), financials[Month Number] = 1)
			var _G2 = CALCULATE(SUM(financials[Gross Sales]), financials[Month Number] = 2)
			var _G3 = CALCULATE(SUM(financials[Gross Sales]), financials[Month Number] = 3)
			var _G4 = CALCULATE(SUM(financials[Gross Sales]), financials[Month Number] = 4)
			var _G5 = CALCULATE(SUM(financials[Gross Sales]), financials[Month Number] = 5)
			var _G6 = CALCULATE(SUM(financials[Gross Sales]), financials[Month Number] = 6)
			var _G7 = CALCULATE(SUM(financials[Gross Sales]), financials[Month Number] = 7)
			var _G8 = CALCULATE(SUM(financials[Gross Sales]), financials[Month Number] = 8)
			var _G9 = CALCULATE(SUM(financials[Gross Sales]), financials[Month Number] = 9)
			var _G10 = CALCULATE(SUM(financials[Gross Sales]), financials[Month Number] = 10)
			var _G11 = CALCULATE(SUM(financials[Gross Sales]), financials[Month Number] = 11)
			var _G12 = CALCULATE(SUM(financials[Gross Sales]), financials[Month Number] = 12)
			var _S1 = CALCULATE(SUM(financials[Sales]), financials[Month Number] = 1)
			var _S2 = CALCULATE(SUM(financials[Sales]), financials[Month Number] = 2)
			var _S3 = CALCULATE(SUM(financials[Sales]), financials[Month Number] = 3)
			var _S4 = CALCULATE(SUM(financials[Sales]), financials[Month Number] = 4)
			var _S5 = CALCULATE(SUM(financials[Sales]), financials[Month Number] = 5)
			var _S6 = CALCULATE(SUM(financials[Sales]), financials[Month Number] = 6)
			var _S7 = CALCULATE(SUM(financials[Sales]), financials[Month Number] = 7)
			var _S8 = CALCULATE(SUM(financials[Sales]), financials[Month Number] = 8)
			var _S9 = CALCULATE(SUM(financials[Sales]), financials[Month Number] = 9)
			var _S10 = CALCULATE(SUM(financials[Sales]), financials[Month Number] = 10)
			var _S11 = CALCULATE(SUM(financials[Sales]), financials[Month Number] = 11)
			var _S12 = CALCULATE(SUM(financials[Sales]), financials[Month Number] = 12)
			var _C1 = CALCULATE(SUM(financials[COGS]), financials[Month Number] = 1)
			var _C2 = CALCULATE(SUM(financials[COGS]), financials[Month Number] = 2)
			var _C3 = CALCULATE(SUM(financials[COGS]), financials[Month Number] = 3)
			var _C4 = CALCULATE(SUM(financials[COGS]), financials[Month Number] = 4)
			var _C5 = CALCULATE(SUM(financials[COGS]), financials[Month Number] = 5)
			var _C6 = CALCULATE(SUM(financials[COGS]), financials[Month Number] = 6)
			var _C7 = CALCULATE(SUM(financials[COGS]), financials[Month Number] = 7)
			var _C8 = CALCULATE(SUM(financials[COGS]), financials[Month Number] = 8)
			var _C9 = CALCULATE(SUM(financials[COGS]), financials[Month Number] = 9)
			var _C10 = CALCULATE(SUM(financials[COGS]), financials[Month Number] = 10)
			var _C11 = CALCULATE(SUM(financials[COGS]), financials[Month Number] = 11)
			var _C12 = CALCULATE(SUM(financials[COGS]), financials[Month Number] = 12)
			var _P1 = CALCULATE(SUM(financials[Profit]), financials[Month Number] = 1)
			var _P2 = CALCULATE(SUM(financials[Profit]), financials[Month Number] = 2)
			var _P3 = CALCULATE(SUM(financials[Profit]), financials[Month Number] = 3)
			var _P4 = CALCULATE(SUM(financials[Profit]), financials[Month Number] = 4)
			var _P5 = CALCULATE(SUM(financials[Profit]), financials[Month Number] = 5)
			var _P6 = CALCULATE(SUM(financials[Profit]), financials[Month Number] = 6)
			var _P7 = CALCULATE(SUM(financials[Profit]), financials[Month Number] = 7)
			var _P8 = CALCULATE(SUM(financials[Profit]), financials[Month Number] = 8)
			var _P9 = CALCULATE(SUM(financials[Profit]), financials[Month Number] = 9)
			var _P10 = CALCULATE(SUM(financials[Profit]), financials[Month Number] = 10)
			var _P11 = CALCULATE(SUM(financials[Profit]), financials[Month Number] = 11)
			var _P12 = CALCULATE(SUM(financials[Profit]), financials[Month Number] = 12)
			var _MaxVal = MAX(MAX(MAX(MAX(MAX(MAX(MAX(MAX(MAX(MAX(MAX(_G1, _G2), _G3), _G4), _G5), _G6), _G7), _G8), _G9), _G10), _G11), _G12)
			var _ChartH = 300
			var _ChartTop = 40
			var _AvgMargin = DIVIDE(SUM(financials[Profit]), SUM(financials[Sales]), 0)
			var _M1 = DIVIDE(_P1, _S1, 0)
			var _M2 = DIVIDE(_P2, _S2, 0)
			var _M3 = DIVIDE(_P3, _S3, 0)
			var _M4 = DIVIDE(_P4, _S4, 0)
			var _M5 = DIVIDE(_P5, _S5, 0)
			var _M6 = DIVIDE(_P6, _S6, 0)
			var _M7 = DIVIDE(_P7, _S7, 0)
			var _M8 = DIVIDE(_P8, _S8, 0)
			var _M9 = DIVIDE(_P9, _S9, 0)
			var _M10 = DIVIDE(_P10, _S10, 0)
			var _M11 = DIVIDE(_P11, _S11, 0)
			var _M12 = DIVIDE(_P12, _S12, 0)
			var _RowCount = FORMAT(COUNTROWS(financials), "#,##0")
			var _MinDate = FORMAT(MIN(financials[Date]), "MMM YYYY")
			var _MaxDate = FORMAT(MAX(financials[Date]), "MMM YYYY")
			var _TotalSales = FORMAT(SUM(financials[Sales]), "#,##0")
			var _TotalProfit = FORMAT(SUM(financials[Profit]), "#,##0")
			var _OverallMargin = FORMAT(_AvgMargin * 100, "0.0")
			return
			"<div style='font-family:Segoe UI,sans-serif;background:#002855;color:#fff;margin:0;padding:0;min-height:100%;box-sizing:border-box'>"
			& "<div style='height:3px;background:linear-gradient(90deg,#E4002B,#00A3E0,#00843D,#FF6900);margin-bottom:0'></div>"
			& "<div style='padding:28px 36px'>"
			& "<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:24px'>"
			& "<div><div style='font-size:10px;color:#00A3E0;text-transform:uppercase;letter-spacing:3px;font-weight:300;margin-bottom:4px'>Monthly Performance</div><h1 style='color:#fff;font-size:26px;margin:0;font-weight:300;letter-spacing:-0.5px'>Candlestick <span style='font-weight:700'>Chart</span></h1></div>"
			& "<div style='text-align:right'><div style='color:#E4002B;font-size:9px;font-weight:600;background:rgba(228,0,43,0.1);border:1px solid rgba(228,0,43,0.3);padding:5px 12px;border-radius:20px;letter-spacing:1px'>&#x25CF; LIVE</div><div style='color:rgba(255,255,255,0.4);font-size:9px;margin-top:4px'>" & _MinDate & " – " & _MaxDate & "</div></div></div>"
			& "<div style='display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:20px'>"
			& "<div style='background:rgba(0,163,224,0.08);border:1px solid rgba(0,163,224,0.15);border-radius:14px;padding:16px;box-shadow:0 8px 32px rgba(0,0,0,0.3)'><div style='color:#00A3E0;font-size:9px;text-transform:uppercase;letter-spacing:2px'>Total Sales</div><div style='font-size:24px;font-weight:700;margin-top:6px;color:#fff'>$" & _TotalSales & "</div></div>"
			& "<div style='background:rgba(0,163,224,0.08);border:1px solid rgba(0,132,61,0.15);border-radius:14px;padding:16px;box-shadow:0 8px 32px rgba(0,0,0,0.3)'><div style='color:#00A3E0;font-size:9px;text-transform:uppercase;letter-spacing:2px'>Total Profit</div><div style='font-size:24px;font-weight:700;margin-top:6px;color:#00843D'>$" & _TotalProfit & "</div></div>"
			& "<div style='background:rgba(0,163,224,0.08);border:1px solid rgba(91,103,112,0.15);border-radius:14px;padding:16px;box-shadow:0 8px 32px rgba(0,0,0,0.3)'><div style='color:#00A3E0;font-size:9px;text-transform:uppercase;letter-spacing:2px'>Avg Margin</div><div style='font-size:24px;font-weight:700;margin-top:6px;color:#7C8A96'>" & _OverallMargin & "%</div></div>"
			& "</div>"
			& "<div style='background:rgba(0,163,224,0.08);border:1px solid rgba(0,163,224,0.15);border-radius:14px;padding:22px;box-shadow:0 8px 32px rgba(0,0,0,0.2);margin-bottom:20px'>"
			& "<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:14px'><div style='color:#00A3E0;font-size:9px;font-weight:600;text-transform:uppercase;letter-spacing:2px'>Monthly Candlestick — Gross Sales / Sales / COGS / Profit</div><div style='font-size:9px'><span style='color:#00843D;margin-right:12px'>&#x25A0; Margin &gt; Avg</span><span style='color:#E4002B'>&#x25A0; Margin &lt; Avg</span></div></div>"
			& "<svg width='100%' viewBox='0 0 1100 380' style='display:block'>"
			& "<rect x='0' y='0' width='1100' height='380' fill='rgba(15,12,41,0.3)' rx='8'/>"
			& "<line x1='60' y1='340' x2='1060' y2='340' stroke='#333' stroke-width='1'/>"
			& "<line x1='60' y1='" & FORMAT(_ChartTop, "0") & "' x2='60' y2='340' stroke='#333' stroke-width='1'/>"
			& "<text x='30' y='" & FORMAT(_ChartTop + 4, "0") & "' fill='#666' font-size='9' text-anchor='middle'>" & FORMAT(_MaxVal / 1000000, "0.0") & "M</text>"
			& "<text x='30' y='175' fill='#666' font-size='9' text-anchor='middle'>" & FORMAT(_MaxVal / 2000000, "0.0") & "M</text>"
			& "<text x='30' y='344' fill='#666' font-size='9' text-anchor='middle'>0</text>"
			& "<line x1='60' y1='170' x2='1060' y2='170' stroke='#002244' stroke-width='0.5' stroke-dasharray='4,4'/>"
			-- Jan candle
			& "<line x1='110' y1='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_G1, _MaxVal, 0) * _ChartH, "0") & "' x2='110' y2='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_P1, _MaxVal, 0) * _ChartH, "0") & "' stroke='" & IF(_M1 >= _AvgMargin, "#00843D", "#E4002B") & "' stroke-width='2'/>"
			& "<rect x='92' y='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_S1, _MaxVal, 0) * _ChartH, "0") & "' width='36' height='" & FORMAT(MAX(DIVIDE(_S1 - _C1, _MaxVal, 0) * _ChartH, 4), "0") & "' fill='" & IF(_M1 >= _AvgMargin, "#00843D", "#E4002B") & "' rx='3' opacity='0.85'/>"
			& "<text x='110' y='358' fill='#888' font-size='9' text-anchor='middle'>Jan</text>"
			-- Feb candle
			& "<line x1='193' y1='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_G2, _MaxVal, 0) * _ChartH, "0") & "' x2='193' y2='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_P2, _MaxVal, 0) * _ChartH, "0") & "' stroke='" & IF(_M2 >= _AvgMargin, "#00843D", "#E4002B") & "' stroke-width='2'/>"
			& "<rect x='175' y='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_S2, _MaxVal, 0) * _ChartH, "0") & "' width='36' height='" & FORMAT(MAX(DIVIDE(_S2 - _C2, _MaxVal, 0) * _ChartH, 4), "0") & "' fill='" & IF(_M2 >= _AvgMargin, "#00843D", "#E4002B") & "' rx='3' opacity='0.85'/>"
			& "<text x='193' y='358' fill='#888' font-size='9' text-anchor='middle'>Feb</text>"
			-- Mar candle
			& "<line x1='276' y1='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_G3, _MaxVal, 0) * _ChartH, "0") & "' x2='276' y2='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_P3, _MaxVal, 0) * _ChartH, "0") & "' stroke='" & IF(_M3 >= _AvgMargin, "#00843D", "#E4002B") & "' stroke-width='2'/>"
			& "<rect x='258' y='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_S3, _MaxVal, 0) * _ChartH, "0") & "' width='36' height='" & FORMAT(MAX(DIVIDE(_S3 - _C3, _MaxVal, 0) * _ChartH, 4), "0") & "' fill='" & IF(_M3 >= _AvgMargin, "#00843D", "#E4002B") & "' rx='3' opacity='0.85'/>"
			& "<text x='276' y='358' fill='#888' font-size='9' text-anchor='middle'>Mar</text>"
			-- Apr candle
			& "<line x1='359' y1='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_G4, _MaxVal, 0) * _ChartH, "0") & "' x2='359' y2='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_P4, _MaxVal, 0) * _ChartH, "0") & "' stroke='" & IF(_M4 >= _AvgMargin, "#00843D", "#E4002B") & "' stroke-width='2'/>"
			& "<rect x='341' y='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_S4, _MaxVal, 0) * _ChartH, "0") & "' width='36' height='" & FORMAT(MAX(DIVIDE(_S4 - _C4, _MaxVal, 0) * _ChartH, 4), "0") & "' fill='" & IF(_M4 >= _AvgMargin, "#00843D", "#E4002B") & "' rx='3' opacity='0.85'/>"
			& "<text x='359' y='358' fill='#888' font-size='9' text-anchor='middle'>Apr</text>"
			-- May candle
			& "<line x1='442' y1='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_G5, _MaxVal, 0) * _ChartH, "0") & "' x2='442' y2='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_P5, _MaxVal, 0) * _ChartH, "0") & "' stroke='" & IF(_M5 >= _AvgMargin, "#00843D", "#E4002B") & "' stroke-width='2'/>"
			& "<rect x='424' y='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_S5, _MaxVal, 0) * _ChartH, "0") & "' width='36' height='" & FORMAT(MAX(DIVIDE(_S5 - _C5, _MaxVal, 0) * _ChartH, 4), "0") & "' fill='" & IF(_M5 >= _AvgMargin, "#00843D", "#E4002B") & "' rx='3' opacity='0.85'/>"
			& "<text x='442' y='358' fill='#888' font-size='9' text-anchor='middle'>May</text>"
			-- Jun candle
			& "<line x1='525' y1='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_G6, _MaxVal, 0) * _ChartH, "0") & "' x2='525' y2='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_P6, _MaxVal, 0) * _ChartH, "0") & "' stroke='" & IF(_M6 >= _AvgMargin, "#00843D", "#E4002B") & "' stroke-width='2'/>"
			& "<rect x='507' y='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_S6, _MaxVal, 0) * _ChartH, "0") & "' width='36' height='" & FORMAT(MAX(DIVIDE(_S6 - _C6, _MaxVal, 0) * _ChartH, 4), "0") & "' fill='" & IF(_M6 >= _AvgMargin, "#00843D", "#E4002B") & "' rx='3' opacity='0.85'/>"
			& "<text x='525' y='358' fill='#888' font-size='9' text-anchor='middle'>Jun</text>"
			-- Jul candle
			& "<line x1='608' y1='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_G7, _MaxVal, 0) * _ChartH, "0") & "' x2='608' y2='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_P7, _MaxVal, 0) * _ChartH, "0") & "' stroke='" & IF(_M7 >= _AvgMargin, "#00843D", "#E4002B") & "' stroke-width='2'/>"
			& "<rect x='590' y='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_S7, _MaxVal, 0) * _ChartH, "0") & "' width='36' height='" & FORMAT(MAX(DIVIDE(_S7 - _C7, _MaxVal, 0) * _ChartH, 4), "0") & "' fill='" & IF(_M7 >= _AvgMargin, "#00843D", "#E4002B") & "' rx='3' opacity='0.85'/>"
			& "<text x='608' y='358' fill='#888' font-size='9' text-anchor='middle'>Jul</text>"
			-- Aug candle
			& "<line x1='691' y1='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_G8, _MaxVal, 0) * _ChartH, "0") & "' x2='691' y2='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_P8, _MaxVal, 0) * _ChartH, "0") & "' stroke='" & IF(_M8 >= _AvgMargin, "#00843D", "#E4002B") & "' stroke-width='2'/>"
			& "<rect x='673' y='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_S8, _MaxVal, 0) * _ChartH, "0") & "' width='36' height='" & FORMAT(MAX(DIVIDE(_S8 - _C8, _MaxVal, 0) * _ChartH, 4), "0") & "' fill='" & IF(_M8 >= _AvgMargin, "#00843D", "#E4002B") & "' rx='3' opacity='0.85'/>"
			& "<text x='691' y='358' fill='#888' font-size='9' text-anchor='middle'>Aug</text>"
			-- Sep candle
			& "<line x1='774' y1='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_G9, _MaxVal, 0) * _ChartH, "0") & "' x2='774' y2='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_P9, _MaxVal, 0) * _ChartH, "0") & "' stroke='" & IF(_M9 >= _AvgMargin, "#00843D", "#E4002B") & "' stroke-width='2'/>"
			& "<rect x='756' y='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_S9, _MaxVal, 0) * _ChartH, "0") & "' width='36' height='" & FORMAT(MAX(DIVIDE(_S9 - _C9, _MaxVal, 0) * _ChartH, 4), "0") & "' fill='" & IF(_M9 >= _AvgMargin, "#00843D", "#E4002B") & "' rx='3' opacity='0.85'/>"
			& "<text x='774' y='358' fill='#888' font-size='9' text-anchor='middle'>Sep</text>"
			-- Oct candle
			& "<line x1='857' y1='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_G10, _MaxVal, 0) * _ChartH, "0") & "' x2='857' y2='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_P10, _MaxVal, 0) * _ChartH, "0") & "' stroke='" & IF(_M10 >= _AvgMargin, "#00843D", "#E4002B") & "' stroke-width='2'/>"
			& "<rect x='839' y='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_S10, _MaxVal, 0) * _ChartH, "0") & "' width='36' height='" & FORMAT(MAX(DIVIDE(_S10 - _C10, _MaxVal, 0) * _ChartH, 4), "0") & "' fill='" & IF(_M10 >= _AvgMargin, "#00843D", "#E4002B") & "' rx='3' opacity='0.85'/>"
			& "<text x='857' y='358' fill='#888' font-size='9' text-anchor='middle'>Oct</text>"
			-- Nov candle
			& "<line x1='940' y1='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_G11, _MaxVal, 0) * _ChartH, "0") & "' x2='940' y2='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_P11, _MaxVal, 0) * _ChartH, "0") & "' stroke='" & IF(_M11 >= _AvgMargin, "#00843D", "#E4002B") & "' stroke-width='2'/>"
			& "<rect x='922' y='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_S11, _MaxVal, 0) * _ChartH, "0") & "' width='36' height='" & FORMAT(MAX(DIVIDE(_S11 - _C11, _MaxVal, 0) * _ChartH, 4), "0") & "' fill='" & IF(_M11 >= _AvgMargin, "#00843D", "#E4002B") & "' rx='3' opacity='0.85'/>"
			& "<text x='940' y='358' fill='#888' font-size='9' text-anchor='middle'>Nov</text>"
			-- Dec candle
			& "<line x1='1023' y1='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_G12, _MaxVal, 0) * _ChartH, "0") & "' x2='1023' y2='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_P12, _MaxVal, 0) * _ChartH, "0") & "' stroke='" & IF(_M12 >= _AvgMargin, "#00843D", "#E4002B") & "' stroke-width='2'/>"
			& "<rect x='1005' y='" & FORMAT(_ChartTop + _ChartH - DIVIDE(_S12, _MaxVal, 0) * _ChartH, "0") & "' width='36' height='" & FORMAT(MAX(DIVIDE(_S12 - _C12, _MaxVal, 0) * _ChartH, 4), "0") & "' fill='" & IF(_M12 >= _AvgMargin, "#00843D", "#E4002B") & "' rx='3' opacity='0.85'/>"
			& "<text x='1023' y='358' fill='#888' font-size='9' text-anchor='middle'>Dec</text>"
			& "</svg></div>"
			& "<div style='display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:14px'>"
			& "<div style='background:rgba(0,163,224,0.06);border-radius:8px;padding:10px;text-align:center;border:1px solid rgba(0,163,224,0.12)'><div style='font-size:8px;color:#888;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:4px'>Wick Top</div><div style='font-size:10px;color:#00A3E0'>Gross Sales</div></div>"
			& "<div style='background:rgba(0,163,224,0.06);border-radius:8px;padding:10px;text-align:center;border:1px solid rgba(0,132,61,0.12)'><div style='font-size:8px;color:#888;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:4px'>Body Top</div><div style='font-size:10px;color:#00843D'>Net Sales</div></div>"
			& "<div style='background:rgba(0,163,224,0.06);border-radius:8px;padding:10px;text-align:center;border:1px solid rgba(255,105,0,0.12)'><div style='font-size:8px;color:#888;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:4px'>Body Bottom</div><div style='font-size:10px;color:#FF6900'>COGS</div></div>"
			& "<div style='background:rgba(0,163,224,0.06);border-radius:8px;padding:10px;text-align:center;border:1px solid rgba(228,0,43,0.12)'><div style='font-size:8px;color:#888;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:4px'>Wick Bottom</div><div style='font-size:10px;color:#E4002B'>Profit</div></div>"
			& "</div>"
			& "<div style='display:flex;justify-content:space-between;align-items:center;padding:12px 0;border-top:1px solid rgba(0,163,224,0.05);margin-top:14px'><div style='font-size:8px;color:rgba(255,255,255,0.25);letter-spacing:1px'>FINANCIAL ANALYTICS PLATFORM</div><div style='font-size:8px;color:rgba(255,255,255,0.25)'>" & _RowCount & " records · Auto-refreshed</div></div>"
			& "</div></div>"
		displayFolder: HTML
		lineageTag: d4e5f6a7-b8c9-4567-def0-456789012345

	/// Multi-dimensional radar chart with 5-segment overlay, correlation heatmap, and sparkline matrix — impossible in native PBI
	measure Radar_Heatmap_HTML =
			// === SEGMENT SALES ===
			var _MaxSales = MAXX(ALL(financials[Segment]), CALCULATE(SUM(financials[Sales])))
			var _GovS = DIVIDE(CALCULATE(SUM(financials[Sales]), financials[Segment]="Government"), _MaxSales, 0)
			var _MidS = DIVIDE(CALCULATE(SUM(financials[Sales]), financials[Segment]="Midmarket"), _MaxSales, 0)
			var _EntS = DIVIDE(CALCULATE(SUM(financials[Sales]), financials[Segment]="Enterprise"), _MaxSales, 0)
			var _SBS = DIVIDE(CALCULATE(SUM(financials[Sales]), financials[Segment]="Small Business"), _MaxSales, 0)
			var _ChS = DIVIDE(CALCULATE(SUM(financials[Sales]), financials[Segment]="Channel Partners"), _MaxSales, 0)
			// === SEGMENT PROFIT MARGIN ===
			var _GovM = DIVIDE(CALCULATE(SUM(financials[Profit]), financials[Segment]="Government"), CALCULATE(SUM(financials[Sales]), financials[Segment]="Government"), 0)
			var _MidM = DIVIDE(CALCULATE(SUM(financials[Profit]), financials[Segment]="Midmarket"), CALCULATE(SUM(financials[Sales]), financials[Segment]="Midmarket"), 0)
			var _EntM = DIVIDE(CALCULATE(SUM(financials[Profit]), financials[Segment]="Enterprise"), CALCULATE(SUM(financials[Sales]), financials[Segment]="Enterprise"), 0)
			var _SBM = DIVIDE(CALCULATE(SUM(financials[Profit]), financials[Segment]="Small Business"), CALCULATE(SUM(financials[Sales]), financials[Segment]="Small Business"), 0)
			var _ChM = DIVIDE(CALCULATE(SUM(financials[Profit]), financials[Segment]="Channel Partners"), CALCULATE(SUM(financials[Sales]), financials[Segment]="Channel Partners"), 0)
			// === SEGMENT UNITS (normalized) ===
			var _MaxUnits = MAXX(ALL(financials[Segment]), CALCULATE(SUM(financials[Units Sold])))
			var _GovU = DIVIDE(CALCULATE(SUM(financials[Units Sold]), financials[Segment]="Government"), _MaxUnits, 0)
			var _MidU = DIVIDE(CALCULATE(SUM(financials[Units Sold]), financials[Segment]="Midmarket"), _MaxUnits, 0)
			var _EntU = DIVIDE(CALCULATE(SUM(financials[Units Sold]), financials[Segment]="Enterprise"), _MaxUnits, 0)
			var _SBU = DIVIDE(CALCULATE(SUM(financials[Units Sold]), financials[Segment]="Small Business"), _MaxUnits, 0)
			var _ChU = DIVIDE(CALCULATE(SUM(financials[Units Sold]), financials[Segment]="Channel Partners"), _MaxUnits, 0)
			// === SEGMENT DISCOUNT RATE ===
			var _GovD = DIVIDE(CALCULATE(SUM(financials[Discounts]), financials[Segment]="Government"), CALCULATE(SUM(financials[Gross Sales]), financials[Segment]="Government"), 0)
			var _MidD = DIVIDE(CALCULATE(SUM(financials[Discounts]), financials[Segment]="Midmarket"), CALCULATE(SUM(financials[Gross Sales]), financials[Segment]="Midmarket"), 0)
			var _EntD = DIVIDE(CALCULATE(SUM(financials[Discounts]), financials[Segment]="Enterprise"), CALCULATE(SUM(financials[Gross Sales]), financials[Segment]="Enterprise"), 0)
			var _SBD = DIVIDE(CALCULATE(SUM(financials[Discounts]), financials[Segment]="Small Business"), CALCULATE(SUM(financials[Gross Sales]), financials[Segment]="Small Business"), 0)
			var _ChD = DIVIDE(CALCULATE(SUM(financials[Discounts]), financials[Segment]="Channel Partners"), CALCULATE(SUM(financials[Gross Sales]), financials[Segment]="Channel Partners"), 0)
			// === SEGMENT COGS RATIO ===
			var _GovC = DIVIDE(CALCULATE(SUM(financials[COGS]), financials[Segment]="Government"), CALCULATE(SUM(financials[Sales]), financials[Segment]="Government"), 0)
			var _MidC = DIVIDE(CALCULATE(SUM(financials[COGS]), financials[Segment]="Midmarket"), CALCULATE(SUM(financials[Sales]), financials[Segment]="Midmarket"), 0)
			var _EntC = DIVIDE(CALCULATE(SUM(financials[COGS]), financials[Segment]="Enterprise"), CALCULATE(SUM(financials[Sales]), financials[Segment]="Enterprise"), 0)
			var _SBC = DIVIDE(CALCULATE(SUM(financials[COGS]), financials[Segment]="Small Business"), CALCULATE(SUM(financials[Sales]), financials[Segment]="Small Business"), 0)
			var _ChC = DIVIDE(CALCULATE(SUM(financials[COGS]), financials[Segment]="Channel Partners"), CALCULATE(SUM(financials[Sales]), financials[Segment]="Channel Partners"), 0)
			// === RADAR GEOMETRY (5 axes, center 160,160, radius 130) ===
			var _cx = 160
			var _cy = 160
			var _r = 130
			// Axis angles: 0=top(-90°), 72° apart → -90, -18, 54, 126, 198
			// Revenue(top), Margin(topR), Volume(botR), DiscRate(botL), COGSRatio(topL)
			// Axis endpoints (x = cx + r*cos(angle), y = cy + r*sin(angle))
			var _ax1x = _cx
			var _ax1y = _cy - _r
			var _ax2x = _cx + ROUND(_r * 0.951, 0)
			var _ax2y = _cy - ROUND(_r * 0.309, 0)
			var _ax3x = _cx + ROUND(_r * 0.588, 0)
			var _ax3y = _cy + ROUND(_r * 0.809, 0)
			var _ax4x = _cx - ROUND(_r * 0.588, 0)
			var _ax4y = _cy + ROUND(_r * 0.809, 0)
			var _ax5x = _cx - ROUND(_r * 0.951, 0)
			var _ax5y = _cy - ROUND(_r * 0.309, 0)
			// Helper: point on axis at distance d (0-1)
			// Gov polygon
			var _gp = FORMAT(_cx + ROUND(_GovS * (_ax1x-_cx), 0), "0") & "," & FORMAT(_cy + ROUND(_GovS * (_ax1y-_cy), 0), "0") & " " & FORMAT(_cx + ROUND(_GovM * (_ax2x-_cx), 0), "0") & "," & FORMAT(_cy + ROUND(_GovM * (_ax2y-_cy), 0), "0") & " " & FORMAT(_cx + ROUND(_GovU * (_ax3x-_cx), 0), "0") & "," & FORMAT(_cy + ROUND(_GovU * (_ax3y-_cy), 0), "0") & " " & FORMAT(_cx + ROUND(_GovD * 3 * (_ax4x-_cx), 0), "0") & "," & FORMAT(_cy + ROUND(_GovD * 3 * (_ax4y-_cy), 0), "0") & " " & FORMAT(_cx + ROUND(_GovC * (_ax5x-_cx), 0), "0") & "," & FORMAT(_cy + ROUND(_GovC * (_ax5y-_cy), 0), "0")
			var _mp = FORMAT(_cx + ROUND(_MidS * (_ax1x-_cx), 0), "0") & "," & FORMAT(_cy + ROUND(_MidS * (_ax1y-_cy), 0), "0") & " " & FORMAT(_cx + ROUND(_MidM * (_ax2x-_cx), 0), "0") & "," & FORMAT(_cy + ROUND(_MidM * (_ax2y-_cy), 0), "0") & " " & FORMAT(_cx + ROUND(_MidU * (_ax3x-_cx), 0), "0") & "," & FORMAT(_cy + ROUND(_MidU * (_ax3y-_cy), 0), "0") & " " & FORMAT(_cx + ROUND(_MidD * 3 * (_ax4x-_cx), 0), "0") & "," & FORMAT(_cy + ROUND(_MidD * 3 * (_ax4y-_cy), 0), "0") & " " & FORMAT(_cx + ROUND(_MidC * (_ax5x-_cx), 0), "0") & "," & FORMAT(_cy + ROUND(_MidC * (_ax5y-_cy), 0), "0")
			var _ep = FORMAT(_cx + ROUND(_EntS * (_ax1x-_cx), 0), "0") & "," & FORMAT(_cy + ROUND(_EntS * (_ax1y-_cy), 0), "0") & " " & FORMAT(_cx + ROUND(_EntM * (_ax2x-_cx), 0), "0") & "," & FORMAT(_cy + ROUND(_EntM * (_ax2y-_cy), 0), "0") & " " & FORMAT(_cx + ROUND(_EntU * (_ax3x-_cx), 0), "0") & "," & FORMAT(_cy + ROUND(_EntU * (_ax3y-_cy), 0), "0") & " " & FORMAT(_cx + ROUND(_EntD * 3 * (_ax4x-_cx), 0), "0") & "," & FORMAT(_cy + ROUND(_EntD * 3 * (_ax4y-_cy), 0), "0") & " " & FORMAT(_cx + ROUND(_EntC * (_ax5x-_cx), 0), "0") & "," & FORMAT(_cy + ROUND(_EntC * (_ax5y-_cy), 0), "0")
			var _sp = FORMAT(_cx + ROUND(_SBS * (_ax1x-_cx), 0), "0") & "," & FORMAT(_cy + ROUND(_SBS * (_ax1y-_cy), 0), "0") & " " & FORMAT(_cx + ROUND(_SBM * (_ax2x-_cx), 0), "0") & "," & FORMAT(_cy + ROUND(_SBM * (_ax2y-_cy), 0), "0") & " " & FORMAT(_cx + ROUND(_SBU * (_ax3x-_cx), 0), "0") & "," & FORMAT(_cy + ROUND(_SBU * (_ax3y-_cy), 0), "0") & " " & FORMAT(_cx + ROUND(_SBD * 3 * (_ax4x-_cx), 0), "0") & "," & FORMAT(_cy + ROUND(_SBD * 3 * (_ax4y-_cy), 0), "0") & " " & FORMAT(_cx + ROUND(_SBC * (_ax5x-_cx), 0), "0") & "," & FORMAT(_cy + ROUND(_SBC * (_ax5y-_cy), 0), "0")
			var _cp = FORMAT(_cx + ROUND(_ChS * (_ax1x-_cx), 0), "0") & "," & FORMAT(_cy + ROUND(_ChS * (_ax1y-_cy), 0), "0") & " " & FORMAT(_cx + ROUND(_ChM * (_ax2x-_cx), 0), "0") & "," & FORMAT(_cy + ROUND(_ChM * (_ax2y-_cy), 0), "0") & " " & FORMAT(_cx + ROUND(_ChU * (_ax3x-_cx), 0), "0") & "," & FORMAT(_cy + ROUND(_ChU * (_ax3y-_cy), 0), "0") & " " & FORMAT(_cx + ROUND(_ChD * 3 * (_ax4x-_cx), 0), "0") & "," & FORMAT(_cy + ROUND(_ChD * 3 * (_ax4y-_cy), 0), "0") & " " & FORMAT(_cx + ROUND(_ChC * (_ax5x-_cx), 0), "0") & "," & FORMAT(_cy + ROUND(_ChC * (_ax5y-_cy), 0), "0")
			// === HEATMAP VALUES (raw for display) ===
			var _GovSF = FORMAT(CALCULATE(SUM(financials[Sales]), financials[Segment]="Government"), "$#,##0")
			var _MidSF = FORMAT(CALCULATE(SUM(financials[Sales]), financials[Segment]="Midmarket"), "$#,##0")
			var _EntSF = FORMAT(CALCULATE(SUM(financials[Sales]), financials[Segment]="Enterprise"), "$#,##0")
			var _SBSF = FORMAT(CALCULATE(SUM(financials[Sales]), financials[Segment]="Small Business"), "$#,##0")
			var _ChSF = FORMAT(CALCULATE(SUM(financials[Sales]), financials[Segment]="Channel Partners"), "$#,##0")
			var _GovMF = FORMAT(_GovM * 100, "0.0") & "%"
			var _MidMF = FORMAT(_MidM * 100, "0.0") & "%"
			var _EntMF = FORMAT(_EntM * 100, "0.0") & "%"
			var _SBMF = FORMAT(_SBM * 100, "0.0") & "%"
			var _ChMF = FORMAT(_ChM * 100, "0.0") & "%"
			var _GovUF = FORMAT(CALCULATE(SUM(financials[Units Sold]), financials[Segment]="Government"), "#,##0")
			var _MidUF = FORMAT(CALCULATE(SUM(financials[Units Sold]), financials[Segment]="Midmarket"), "#,##0")
			var _EntUF = FORMAT(CALCULATE(SUM(financials[Units Sold]), financials[Segment]="Enterprise"), "#,##0")
			var _SBUF = FORMAT(CALCULATE(SUM(financials[Units Sold]), financials[Segment]="Small Business"), "#,##0")
			var _ChUF = FORMAT(CALCULATE(SUM(financials[Units Sold]), financials[Segment]="Channel Partners"), "#,##0")
			var _RowCount = FORMAT(COUNTROWS(financials), "#,##0")
			var _MinDate = FORMAT(MIN(financials[Date]), "MMM YYYY")
			var _MaxDate = FORMAT(MAX(financials[Date]), "MMM YYYY")
			// === HEATMAP COLOR FUNCTION (intensity 0-1 → rgba) ===
			// Using pre-computed opacity strings
			var _GovSO = FORMAT(_GovS, "0.00")
			var _MidSO = FORMAT(_MidS, "0.00")
			var _EntSO = FORMAT(_EntS, "0.00")
			var _SBSO = FORMAT(_SBS, "0.00")
			var _ChSO = FORMAT(_ChS, "0.00")
			var _GovMO = FORMAT(_GovM * 2.5, "0.00")
			var _MidMO = FORMAT(_MidM * 2.5, "0.00")
			var _EntMO = FORMAT(_EntM * 2.5, "0.00")
			var _SBMO = FORMAT(_SBM * 2.5, "0.00")
			var _ChMO = FORMAT(_ChM * 2.5, "0.00")
			var _GovUO = FORMAT(_GovU, "0.00")
			var _MidUO = FORMAT(_MidU, "0.00")
			var _EntUO = FORMAT(_EntU, "0.00")
			var _SBUO = FORMAT(_SBU, "0.00")
			var _ChUO = FORMAT(_ChU, "0.00")
			return
			"<div style='font-family:Segoe UI,sans-serif;background:#002855;color:#fff;margin:0;padding:0;min-height:100%;box-sizing:border-box'>"
			& "<div style='height:3px;background:linear-gradient(90deg,#E4002B,#00A3E0,#00843D,#FF6900,#7C8A96);margin-bottom:0'></div>"
			& "<div style='padding:20px 28px'>"
			& "<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:16px'>"
			& "<div><div style='font-size:9px;color:#00A3E0;text-transform:uppercase;letter-spacing:3px;font-weight:300;margin-bottom:4px'>Advanced Analytics</div><h1 style='color:#fff;font-size:22px;margin:0;font-weight:300'>Segment <span style='font-weight:700'>Radar Matrix</span></h1></div>"
			& "<div style='text-align:right'><div style='color:#7C8A96;font-size:9px;font-weight:600;background:rgba(124,138,150,0.1);border:1px solid rgba(124,138,150,0.3);padding:4px 10px;border-radius:20px;letter-spacing:1px'>&#x25CF; SVG RADAR + HEATMAP</div><div style='color:rgba(255,255,255,0.4);font-size:9px;margin-top:3px'>" & _MinDate & " – " & _MaxDate & "</div></div></div>"
			& "<div style='display:grid;grid-template-columns:340px 1fr;gap:16px'>"
			& "<div style='background:rgba(0,163,224,0.08);border:1px solid rgba(0,163,224,0.15);border-radius:14px;padding:16px;box-shadow:0 8px 32px rgba(0,0,0,0.2)'>"
			& "<div style='color:#00A3E0;font-size:8px;font-weight:600;text-transform:uppercase;letter-spacing:2px;margin-bottom:8px;text-align:center'>5-Axis Performance Radar</div>"
			& "<svg width='320' height='320' viewBox='0 0 320 320'>"
			& "<polygon points='" & FORMAT(_ax1x,"0") & "," & FORMAT(_ax1y,"0") & " " & FORMAT(_ax2x,"0") & "," & FORMAT(_ax2y,"0") & " " & FORMAT(_ax3x,"0") & "," & FORMAT(_ax3y,"0") & " " & FORMAT(_ax4x,"0") & "," & FORMAT(_ax4y,"0") & " " & FORMAT(_ax5x,"0") & "," & FORMAT(_ax5y,"0") & "' fill='none' stroke='rgba(0,163,224,0.1)' stroke-width='1'/>"
			& "<polygon points='" & FORMAT(_cx+ROUND(0.66*(_ax1x-_cx),0),"0") & "," & FORMAT(_cy+ROUND(0.66*(_ax1y-_cy),0),"0") & " " & FORMAT(_cx+ROUND(0.66*(_ax2x-_cx),0),"0") & "," & FORMAT(_cy+ROUND(0.66*(_ax2y-_cy),0),"0") & " " & FORMAT(_cx+ROUND(0.66*(_ax3x-_cx),0),"0") & "," & FORMAT(_cy+ROUND(0.66*(_ax3y-_cy),0),"0") & " " & FORMAT(_cx+ROUND(0.66*(_ax4x-_cx),0),"0") & "," & FORMAT(_cy+ROUND(0.66*(_ax4y-_cy),0),"0") & " " & FORMAT(_cx+ROUND(0.66*(_ax5x-_cx),0),"0") & "," & FORMAT(_cy+ROUND(0.66*(_ax5y-_cy),0),"0") & "' fill='none' stroke='rgba(0,163,224,0.07)' stroke-width='1'/>"
			& "<polygon points='" & FORMAT(_cx+ROUND(0.33*(_ax1x-_cx),0),"0") & "," & FORMAT(_cy+ROUND(0.33*(_ax1y-_cy),0),"0") & " " & FORMAT(_cx+ROUND(0.33*(_ax2x-_cx),0),"0") & "," & FORMAT(_cy+ROUND(0.33*(_ax2y-_cy),0),"0") & " " & FORMAT(_cx+ROUND(0.33*(_ax3x-_cx),0),"0") & "," & FORMAT(_cy+ROUND(0.33*(_ax3y-_cy),0),"0") & " " & FORMAT(_cx+ROUND(0.33*(_ax4x-_cx),0),"0") & "," & FORMAT(_cy+ROUND(0.33*(_ax4y-_cy),0),"0") & " " & FORMAT(_cx+ROUND(0.33*(_ax5x-_cx),0),"0") & "," & FORMAT(_cy+ROUND(0.33*(_ax5y-_cy),0),"0") & "' fill='none' stroke='rgba(0,163,224,0.05)' stroke-width='1'/>"
			& "<line x1='" & FORMAT(_cx,"0") & "' y1='" & FORMAT(_cy,"0") & "' x2='" & FORMAT(_ax1x,"0") & "' y2='" & FORMAT(_ax1y,"0") & "' stroke='rgba(0,163,224,0.15)' stroke-width='1'/>"
			& "<line x1='" & FORMAT(_cx,"0") & "' y1='" & FORMAT(_cy,"0") & "' x2='" & FORMAT(_ax2x,"0") & "' y2='" & FORMAT(_ax2y,"0") & "' stroke='rgba(0,163,224,0.15)' stroke-width='1'/>"
			& "<line x1='" & FORMAT(_cx,"0") & "' y1='" & FORMAT(_cy,"0") & "' x2='" & FORMAT(_ax3x,"0") & "' y2='" & FORMAT(_ax3y,"0") & "' stroke='rgba(0,163,224,0.15)' stroke-width='1'/>"
			& "<line x1='" & FORMAT(_cx,"0") & "' y1='" & FORMAT(_cy,"0") & "' x2='" & FORMAT(_ax4x,"0") & "' y2='" & FORMAT(_ax4y,"0") & "' stroke='rgba(0,163,224,0.15)' stroke-width='1'/>"
			& "<line x1='" & FORMAT(_cx,"0") & "' y1='" & FORMAT(_cy,"0") & "' x2='" & FORMAT(_ax5x,"0") & "' y2='" & FORMAT(_ax5y,"0") & "' stroke='rgba(0,163,224,0.15)' stroke-width='1'/>"
			& "<polygon points='" & _gp & "' fill='rgba(228,0,43,0.15)' stroke='#E4002B' stroke-width='2' stroke-linejoin='round'/>"
			& "<polygon points='" & _mp & "' fill='rgba(124,138,150,0.12)' stroke='#7C8A96' stroke-width='2' stroke-linejoin='round'/>"
			& "<polygon points='" & _ep & "' fill='rgba(0,163,224,0.12)' stroke='#00A3E0' stroke-width='2' stroke-linejoin='round'/>"
			& "<polygon points='" & _sp & "' fill='rgba(0,132,61,0.12)' stroke='#00843D' stroke-width='2' stroke-linejoin='round'/>"
			& "<polygon points='" & _cp & "' fill='rgba(255,105,0,0.12)' stroke='#FF6900' stroke-width='2' stroke-linejoin='round'/>"
			& "<text x='160' y='18' text-anchor='middle' fill='#00A3E0' font-size='9' font-weight='600'>REVENUE</text>"
			& "<text x='300' y='120' text-anchor='start' fill='#00843D' font-size='9' font-weight='600'>MARGIN</text>"
			& "<text x='250' y='290' text-anchor='middle' fill='#7C8A96' font-size='9' font-weight='600'>VOLUME</text>"
			& "<text x='70' y='290' text-anchor='middle' fill='#FF6900' font-size='9' font-weight='600'>DISC RATE</text>"
			& "<text x='20' y='120' text-anchor='end' fill='#E4002B' font-size='9' font-weight='600'>COGS</text>"
			& "</svg>"
			& "<div style='display:flex;flex-wrap:wrap;justify-content:center;gap:8px;margin-top:6px'>"
			& "<div style='display:flex;align-items:center;gap:4px'><div style='width:10px;height:3px;background:#E4002B;border-radius:2px'></div><span style='font-size:8px;color:#888'>Gov</span></div>"
			& "<div style='display:flex;align-items:center;gap:4px'><div style='width:10px;height:3px;background:#7C8A96;border-radius:2px'></div><span style='font-size:8px;color:#888'>Mid</span></div>"
			& "<div style='display:flex;align-items:center;gap:4px'><div style='width:10px;height:3px;background:#00A3E0;border-radius:2px'></div><span style='font-size:8px;color:#888'>Ent</span></div>"
			& "<div style='display:flex;align-items:center;gap:4px'><div style='width:10px;height:3px;background:#00843D;border-radius:2px'></div><span style='font-size:8px;color:#888'>SB</span></div>"
			& "<div style='display:flex;align-items:center;gap:4px'><div style='width:10px;height:3px;background:#FF6900;border-radius:2px'></div><span style='font-size:8px;color:#888'>Ch</span></div>"
			& "</div></div>"
			& "<div style='background:rgba(0,163,224,0.08);border:1px solid rgba(0,163,224,0.15);border-radius:14px;padding:16px;box-shadow:0 8px 32px rgba(0,0,0,0.2)'>"
			& "<div style='color:#00A3E0;font-size:8px;font-weight:600;text-transform:uppercase;letter-spacing:2px;margin-bottom:10px'>Performance Heatmap — Intensity = Relative Strength</div>"
			& "<div style='display:grid;grid-template-columns:90px repeat(5,1fr);gap:2px;margin-bottom:2px'>"
			& "<div style='padding:6px;font-size:8px;color:rgba(255,255,255,0.3)'></div>"
			& "<div style='padding:6px;text-align:center;font-size:8px;color:#E4002B;font-weight:600'>GOV</div>"
			& "<div style='padding:6px;text-align:center;font-size:8px;color:#7C8A96;font-weight:600'>MID</div>"
			& "<div style='padding:6px;text-align:center;font-size:8px;color:#00A3E0;font-weight:600'>ENT</div>"
			& "<div style='padding:6px;text-align:center;font-size:8px;color:#00843D;font-weight:600'>SB</div>"
			& "<div style='padding:6px;text-align:center;font-size:8px;color:#FF6900;font-weight:600'>CH</div></div>"
			& "<div style='display:grid;grid-template-columns:90px repeat(5,1fr);gap:2px;margin-bottom:2px'>"
			& "<div style='padding:8px;font-size:9px;color:#00A3E0;font-weight:500;display:flex;align-items:center'>&#9632; Revenue</div>"
			& "<div style='padding:8px;text-align:center;background:rgba(0,163,224," & _GovSO & ");border-radius:6px;font-size:9px;font-weight:600'>" & _GovSF & "</div>"
			& "<div style='padding:8px;text-align:center;background:rgba(0,163,224," & _MidSO & ");border-radius:6px;font-size:9px;font-weight:600'>" & _MidSF & "</div>"
			& "<div style='padding:8px;text-align:center;background:rgba(0,163,224," & _EntSO & ");border-radius:6px;font-size:9px;font-weight:600'>" & _EntSF & "</div>"
			& "<div style='padding:8px;text-align:center;background:rgba(0,163,224," & _SBSO & ");border-radius:6px;font-size:9px;font-weight:600'>" & _SBSF & "</div>"
			& "<div style='padding:8px;text-align:center;background:rgba(0,163,224," & _ChSO & ");border-radius:6px;font-size:9px;font-weight:600'>" & _ChSF & "</div></div>"
			& "<div style='display:grid;grid-template-columns:90px repeat(5,1fr);gap:2px;margin-bottom:2px'>"
			& "<div style='padding:8px;font-size:9px;color:#00843D;font-weight:500;display:flex;align-items:center'>&#9632; Margin</div>"
			& "<div style='padding:8px;text-align:center;background:rgba(0,132,61," & _GovMO & ");border-radius:6px;font-size:9px;font-weight:600'>" & _GovMF & "</div>"
			& "<div style='padding:8px;text-align:center;background:rgba(0,132,61," & _MidMO & ");border-radius:6px;font-size:9px;font-weight:600'>" & _MidMF & "</div>"
			& "<div style='padding:8px;text-align:center;background:rgba(0,132,61," & _EntMO & ");border-radius:6px;font-size:9px;font-weight:600'>" & _EntMF & "</div>"
			& "<div style='padding:8px;text-align:center;background:rgba(0,132,61," & _SBMO & ");border-radius:6px;font-size:9px;font-weight:600'>" & _SBMF & "</div>"
			& "<div style='padding:8px;text-align:center;background:rgba(0,132,61," & _ChMO & ");border-radius:6px;font-size:9px;font-weight:600'>" & _ChMF & "</div></div>"
			& "<div style='display:grid;grid-template-columns:90px repeat(5,1fr);gap:2px;margin-bottom:2px'>"
			& "<div style='padding:8px;font-size:9px;color:#7C8A96;font-weight:500;display:flex;align-items:center'>&#9632; Volume</div>"
			& "<div style='padding:8px;text-align:center;background:rgba(124,138,150," & _GovUO & ");border-radius:6px;font-size:9px;font-weight:600'>" & _GovUF & "</div>"
			& "<div style='padding:8px;text-align:center;background:rgba(124,138,150," & _MidUO & ");border-radius:6px;font-size:9px;font-weight:600'>" & _MidUF & "</div>"
			& "<div style='padding:8px;text-align:center;background:rgba(124,138,150," & _EntUO & ");border-radius:6px;font-size:9px;font-weight:600'>" & _EntUF & "</div>"
			& "<div style='padding:8px;text-align:center;background:rgba(124,138,150," & _SBUO & ");border-radius:6px;font-size:9px;font-weight:600'>" & _SBUF & "</div>"
			& "<div style='padding:8px;text-align:center;background:rgba(124,138,150," & _ChUO & ");border-radius:6px;font-size:9px;font-weight:600'>" & _ChUF & "</div></div>"
			& "<div style='display:grid;grid-template-columns:90px repeat(5,1fr);gap:2px;margin-bottom:2px'>"
			& "<div style='padding:8px;font-size:9px;color:#FF6900;font-weight:500;display:flex;align-items:center'>&#9632; Disc Rate</div>"
			& "<div style='padding:8px;text-align:center;background:rgba(255,105,0," & FORMAT(_GovD*4,"0.00") & ");border-radius:6px;font-size:9px;font-weight:600'>" & FORMAT(_GovD*100,"0.0") & "%</div>"
			& "<div style='padding:8px;text-align:center;background:rgba(255,105,0," & FORMAT(_MidD*4,"0.00") & ");border-radius:6px;font-size:9px;font-weight:600'>" & FORMAT(_MidD*100,"0.0") & "%</div>"
			& "<div style='padding:8px;text-align:center;background:rgba(255,105,0," & FORMAT(_EntD*4,"0.00") & ");border-radius:6px;font-size:9px;font-weight:600'>" & FORMAT(_EntD*100,"0.0") & "%</div>"
			& "<div style='padding:8px;text-align:center;background:rgba(255,105,0," & FORMAT(_SBD*4,"0.00") & ");border-radius:6px;font-size:9px;font-weight:600'>" & FORMAT(_SBD*100,"0.0") & "%</div>"
			& "<div style='padding:8px;text-align:center;background:rgba(255,105,0," & FORMAT(_ChD*4,"0.00") & ");border-radius:6px;font-size:9px;font-weight:600'>" & FORMAT(_ChD*100,"0.0") & "%</div></div>"
			& "<div style='display:grid;grid-template-columns:90px repeat(5,1fr);gap:2px'>"
			& "<div style='padding:8px;font-size:9px;color:#E4002B;font-weight:500;display:flex;align-items:center'>&#9632; COGS %</div>"
			& "<div style='padding:8px;text-align:center;background:rgba(228,0,43," & FORMAT(_GovC,"0.00") & ");border-radius:6px;font-size:9px;font-weight:600'>" & FORMAT(_GovC*100,"0.0") & "%</div>"
			& "<div style='padding:8px;text-align:center;background:rgba(228,0,43," & FORMAT(_MidC,"0.00") & ");border-radius:6px;font-size:9px;font-weight:600'>" & FORMAT(_MidC*100,"0.0") & "%</div>"
			& "<div style='padding:8px;text-align:center;background:rgba(228,0,43," & FORMAT(_EntC,"0.00") & ");border-radius:6px;font-size:9px;font-weight:600'>" & FORMAT(_EntC*100,"0.0") & "%</div>"
			& "<div style='padding:8px;text-align:center;background:rgba(228,0,43," & FORMAT(_SBC,"0.00") & ");border-radius:6px;font-size:9px;font-weight:600'>" & FORMAT(_SBC*100,"0.0") & "%</div>"
			& "<div style='padding:8px;text-align:center;background:rgba(228,0,43," & FORMAT(_ChC,"0.00") & ");border-radius:6px;font-size:9px;font-weight:600'>" & FORMAT(_ChC*100,"0.0") & "%</div></div>"
			& "<div style='margin-top:12px;padding:10px 14px;background:rgba(0,163,224,0.05);border:1px solid rgba(0,163,224,0.1);border-radius:8px'>"
			& "<div style='font-size:8px;color:#00A3E0;font-weight:600;margin-bottom:4px;text-transform:uppercase;letter-spacing:1px'>&#9733; Insight</div>"
			& "<div style='font-size:9px;color:#ccc;line-height:1.5'>Cell intensity encodes relative performance. Brighter cells = higher share of maximum. Radar polygons show each segment's competitive profile across all 5 KPI axes simultaneously — a visualization impossible with any single native Power BI chart type.</div>"
			& "</div></div></div>"
			& "<div style='display:flex;justify-content:space-between;align-items:center;padding:10px 0;border-top:1px solid rgba(0,163,224,0.05);margin-top:14px'><div style='font-size:8px;color:rgba(255,255,255,0.25);letter-spacing:1px'>MULTI-DIMENSIONAL ANALYTICS ENGINE</div><div style='font-size:8px;color:rgba(255,255,255,0.25)'>" & _RowCount & " records · " & _MinDate & " – " & _MaxDate & "</div></div>"
			& "</div></div>"
		displayFolder: HTML
		lineageTag: e6f7a8b9-c0d1-4234-ef56-789012345678

	/// Detailed P&L statement with line-item waterfall, monthly sparklines, and segment margin comparison
	measure PnL_Statement_HTML =
			var _GrossSales = SUM(financials[Gross Sales])
			var _Discounts  = SUM(financials[Discounts])
			var _NetSales   = SUM(financials[Sales])
			var _COGS       = SUM(financials[COGS])
			var _GrossProfit = _NetSales - _COGS
			var _NetProfit  = SUM(financials[Profit])
			var _Units      = SUM(financials[Units Sold])
			var _GrossMargin = DIVIDE(_GrossProfit, _NetSales, 0) * 100
			var _NetMargin  = DIVIDE(_NetProfit, _NetSales, 0) * 100
			var _DiscRate   = DIVIDE(_Discounts, _GrossSales, 0) * 100
			var _COGSRate   = DIVIDE(_COGS, _NetSales, 0) * 100
			var _RowCount   = FORMAT(COUNTROWS(financials), "#,##0")
			var _MinDate    = FORMAT(MIN(financials[Date]), "MMM YYYY")
			var _MaxDate    = FORMAT(MAX(financials[Date]), "MMM YYYY")
			// Formatted values
			var _fGross     = FORMAT(_GrossSales, "$#,##0")
			var _fDisc      = FORMAT(_Discounts, "$#,##0")
			var _fNet       = FORMAT(_NetSales, "$#,##0")
			var _fCOGS      = FORMAT(_COGS, "$#,##0")
			var _fGP        = FORMAT(_GrossProfit, "$#,##0")
			var _fNP        = FORMAT(_NetProfit, "$#,##0")
			var _fGM        = FORMAT(_GrossMargin, "0.0")
			var _fNM        = FORMAT(_NetMargin, "0.0")
			var _fDR        = FORMAT(_DiscRate, "0.0")
			var _fCR        = FORMAT(_COGSRate, "0.0")
			// Monthly Net Profit for sparkline (normalized 0-100)
			var _MP1  = CALCULATE(SUM(financials[Profit]), financials[Month Number]=1)
			var _MP2  = CALCULATE(SUM(financials[Profit]), financials[Month Number]=2)
			var _MP3  = CALCULATE(SUM(financials[Profit]), financials[Month Number]=3)
			var _MP4  = CALCULATE(SUM(financials[Profit]), financials[Month Number]=4)
			var _MP5  = CALCULATE(SUM(financials[Profit]), financials[Month Number]=5)
			var _MP6  = CALCULATE(SUM(financials[Profit]), financials[Month Number]=6)
			var _MP7  = CALCULATE(SUM(financials[Profit]), financials[Month Number]=7)
			var _MP8  = CALCULATE(SUM(financials[Profit]), financials[Month Number]=8)
			var _MP9  = CALCULATE(SUM(financials[Profit]), financials[Month Number]=9)
			var _MP10 = CALCULATE(SUM(financials[Profit]), financials[Month Number]=10)
			var _MP11 = CALCULATE(SUM(financials[Profit]), financials[Month Number]=11)
			var _MP12 = CALCULATE(SUM(financials[Profit]), financials[Month Number]=12)
			var _MaxMP = MAX(MAX(MAX(MAX(MAX(MAX(MAX(MAX(MAX(MAX(MAX(_MP1,_MP2),_MP3),_MP4),_MP5),_MP6),_MP7),_MP8),_MP9),_MP10),_MP11),_MP12)
			var _n1  = FORMAT(ROUND(DIVIDE(_MP1, _MaxMP,0)*60,0),"0")
			var _n2  = FORMAT(ROUND(DIVIDE(_MP2, _MaxMP,0)*60,0),"0")
			var _n3  = FORMAT(ROUND(DIVIDE(_MP3, _MaxMP,0)*60,0),"0")
			var _n4  = FORMAT(ROUND(DIVIDE(_MP4, _MaxMP,0)*60,0),"0")
			var _n5  = FORMAT(ROUND(DIVIDE(_MP5, _MaxMP,0)*60,0),"0")
			var _n6  = FORMAT(ROUND(DIVIDE(_MP6, _MaxMP,0)*60,0),"0")
			var _n7  = FORMAT(ROUND(DIVIDE(_MP7, _MaxMP,0)*60,0),"0")
			var _n8  = FORMAT(ROUND(DIVIDE(_MP8, _MaxMP,0)*60,0),"0")
			var _n9  = FORMAT(ROUND(DIVIDE(_MP9, _MaxMP,0)*60,0),"0")
			var _n10 = FORMAT(ROUND(DIVIDE(_MP10,_MaxMP,0)*60,0),"0")
			var _n11 = FORMAT(ROUND(DIVIDE(_MP11,_MaxMP,0)*60,0),"0")
			var _n12 = FORMAT(ROUND(DIVIDE(_MP12,_MaxMP,0)*60,0),"0")
			// Monthly Sales for sparkline
			var _MS1  = CALCULATE(SUM(financials[Sales]), financials[Month Number]=1)
			var _MS2  = CALCULATE(SUM(financials[Sales]), financials[Month Number]=2)
			var _MS3  = CALCULATE(SUM(financials[Sales]), financials[Month Number]=3)
			var _MS4  = CALCULATE(SUM(financials[Sales]), financials[Month Number]=4)
			var _MS5  = CALCULATE(SUM(financials[Sales]), financials[Month Number]=5)
			var _MS6  = CALCULATE(SUM(financials[Sales]), financials[Month Number]=6)
			var _MS7  = CALCULATE(SUM(financials[Sales]), financials[Month Number]=7)
			var _MS8  = CALCULATE(SUM(financials[Sales]), financials[Month Number]=8)
			var _MS9  = CALCULATE(SUM(financials[Sales]), financials[Month Number]=9)
			var _MS10 = CALCULATE(SUM(financials[Sales]), financials[Month Number]=10)
			var _MS11 = CALCULATE(SUM(financials[Sales]), financials[Month Number]=11)
			var _MS12 = CALCULATE(SUM(financials[Sales]), financials[Month Number]=12)
			var _MaxMS = MAX(MAX(MAX(MAX(MAX(MAX(MAX(MAX(MAX(MAX(MAX(_MS1,_MS2),_MS3),_MS4),_MS5),_MS6),_MS7),_MS8),_MS9),_MS10),_MS11),_MS12)
			var _s1  = FORMAT(ROUND(DIVIDE(_MS1, _MaxMS,0)*60,0),"0")
			var _s2  = FORMAT(ROUND(DIVIDE(_MS2, _MaxMS,0)*60,0),"0")
			var _s3  = FORMAT(ROUND(DIVIDE(_MS3, _MaxMS,0)*60,0),"0")
			var _s4  = FORMAT(ROUND(DIVIDE(_MS4, _MaxMS,0)*60,0),"0")
			var _s5  = FORMAT(ROUND(DIVIDE(_MS5, _MaxMS,0)*60,0),"0")
			var _s6  = FORMAT(ROUND(DIVIDE(_MS6, _MaxMS,0)*60,0),"0")
			var _s7  = FORMAT(ROUND(DIVIDE(_MS7, _MaxMS,0)*60,0),"0")
			var _s8  = FORMAT(ROUND(DIVIDE(_MS8, _MaxMS,0)*60,0),"0")
			var _s9  = FORMAT(ROUND(DIVIDE(_MS9, _MaxMS,0)*60,0),"0")
			var _s10 = FORMAT(ROUND(DIVIDE(_MS10,_MaxMS,0)*60,0),"0")
			var _s11 = FORMAT(ROUND(DIVIDE(_MS11,_MaxMS,0)*60,0),"0")
			var _s12 = FORMAT(ROUND(DIVIDE(_MS12,_MaxMS,0)*60,0),"0")
			// Segment margins
			var _GovM = FORMAT(DIVIDE(CALCULATE(SUM(financials[Profit]),financials[Segment]="Government"), CALCULATE(SUM(financials[Sales]),financials[Segment]="Government"),0)*100,"0.0")
			var _MidM = FORMAT(DIVIDE(CALCULATE(SUM(financials[Profit]),financials[Segment]="Midmarket"), CALCULATE(SUM(financials[Sales]),financials[Segment]="Midmarket"),0)*100,"0.0")
			var _EntM = FORMAT(DIVIDE(CALCULATE(SUM(financials[Profit]),financials[Segment]="Enterprise"), CALCULATE(SUM(financials[Sales]),financials[Segment]="Enterprise"),0)*100,"0.0")
			var _SBM  = FORMAT(DIVIDE(CALCULATE(SUM(financials[Profit]),financials[Segment]="Small Business"), CALCULATE(SUM(financials[Sales]),financials[Segment]="Small Business"),0)*100,"0.0")
			var _ChM  = FORMAT(DIVIDE(CALCULATE(SUM(financials[Profit]),financials[Segment]="Channel Partners"), CALCULATE(SUM(financials[Sales]),financials[Segment]="Channel Partners"),0)*100,"0.0")
			// Waterfall bar widths (relative to Gross Sales = 100%)
			var _wDisc = FORMAT(ROUND(_DiscRate, 0), "0")
			var _wCOGS = FORMAT(ROUND(DIVIDE(_COGS, _GrossSales, 0) * 100, 0), "0")
			var _wGP   = FORMAT(ROUND(DIVIDE(_GrossProfit, _GrossSales, 0) * 100, 0), "0")
			var _wNP   = FORMAT(ROUND(DIVIDE(_NetProfit, _GrossSales, 0) * 100, 0), "0")
			return
			"<style>
			*{box-sizing:border-box;margin:0;padding:0}
			.pw{font-family:'Segoe UI',sans-serif;background:#002855;color:#fff;padding:32px;min-height:600px;position:relative;overflow:hidden}
			.psl{position:absolute;top:0;left:0;right:0;bottom:0;background:repeating-linear-gradient(0deg,transparent,transparent 2px,rgba(0,163,224,0.012) 2px,rgba(0,163,224,0.012) 4px);pointer-events:none}
			.ptb{height:3px;background:linear-gradient(90deg,#5B6770,#00A3E0);margin-bottom:28px;position:relative}
			.ptb::after{content:'';position:absolute;top:-2px;left:0;width:40px;height:7px;background:#00A3E0;filter:blur(4px);animation:pslide 3s ease-in-out infinite}
			@keyframes pslide{0%,100%{left:0;opacity:1}50%{left:calc(100% - 40px);opacity:0.6}}
			.phdr{display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:28px}
			.pht{font-size:11px;color:#00A3E0;text-transform:uppercase;letter-spacing:2px;font-weight:600;margin-bottom:6px}
			.phh{font-size:28px;color:#fff;font-weight:300;letter-spacing:-0.5px}
			.phh b{font-weight:700}
			.pdr{color:rgba(255,255,255,0.4);font-size:11px}
			.pmg{display:grid;grid-template-columns:1.5fr 0.5fr;gap:16px;margin-bottom:24px}
			.ppnl{background:rgba(0,163,224,0.06);border:1px solid rgba(0,163,224,0.12);border-radius:8px;padding:24px}
			.psec{font-size:10px;text-transform:uppercase;letter-spacing:1.5px;color:#00A3E0;font-weight:600;margin-bottom:16px;display:flex;align-items:center;gap:8px}
			.psec::before{content:'';width:16px;height:1px;background:linear-gradient(90deg,#00A3E0,transparent)}
			table.ledger{width:100%;border-collapse:collapse;font-size:11px}
			table.ledger th{font-size:9px;color:rgba(255,255,255,0.35);text-transform:uppercase;letter-spacing:1.5px;font-weight:600;padding:0 0 10px;border-bottom:1px solid rgba(255,255,255,0.1)}
			table.ledger th:nth-child(2),table.ledger th:nth-child(3){text-align:right}
			table.ledger td{padding:8px 0;border-bottom:1px solid rgba(255,255,255,0.04)}
			table.ledger td:nth-child(2),table.ledger td:nth-child(3){text-align:right;font-family:Consolas,monospace;font-size:12px}
			table.ledger tr.indent td:first-child{padding-left:20px;color:rgba(255,255,255,0.55)}
			table.ledger tr.sub td{border-top:1px solid rgba(0,163,224,0.15);border-bottom:1px solid rgba(0,163,224,0.15);font-weight:600}
			table.ledger tr.sub td:nth-child(2){color:#00A3E0}
			table.ledger tr.total td{border-top:2px solid rgba(0,163,224,0.3);border-bottom:3px double rgba(0,163,224,0.3);font-weight:700;font-size:13px;padding:12px 0}
			table.ledger tr.total td:nth-child(2){color:#00A3E0;font-size:14px}
			.pct{color:rgba(255,255,255,0.3);font-size:10px}
			.neg{color:#7C8A96}
			.prp{background:rgba(0,163,224,0.06);border:1px solid rgba(0,163,224,0.12);border-radius:8px;padding:24px;display:flex;flex-direction:column;gap:16px}
			.prbox{flex:1}
			.prbar{background:rgba(0,0,0,0.3);border-radius:3px;height:6px;overflow:hidden;margin-top:6px}
			.prfill{height:100%;border-radius:3px;position:relative;animation:pgrow 1.4s cubic-bezier(0.4,0,0.2,1) forwards}
			@keyframes pgrow{from{width:0}}.prfill::after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,transparent,rgba(255,255,255,0.08),transparent);animation:psh 2s ease-in-out infinite}
			@keyframes psh{0%{transform:translateX(-100%)}100%{transform:translateX(100%)}}
			.pbb{display:flex;justify-content:space-between;align-items:center;padding-top:16px;border-top:1px solid rgba(255,255,255,0.06)}
			.pbl{font-size:9px;color:rgba(255,255,255,0.2);letter-spacing:1.5px;text-transform:uppercase}
			.ptk{display:flex;gap:24px}
			.pti{font-size:9px;color:rgba(255,255,255,0.25)}
			.pti b{color:#00A3E0;font-weight:600}
			</style>
			<div class='pw'>
			<div class='psl'></div>
			<div class='ptb'></div>
			<div class='phdr'>
			  <div>
			    <div class='pht'>Income Statement</div>
			    <div class='phh'>Profit &amp; <b>Loss</b></div>
			  </div>
			  <div class='pdr'>" & _MinDate & " – " & _MaxDate & "</div>
			</div>
			<div class='pmg'>
			  <div class='ppnl'>
			    <div class='psec'>Statement of Operations</div>
			    <table class='ledger'>
			    <thead><tr><th style='text-align:left'>Line Item</th><th>Amount</th><th>% Rev</th></tr></thead>
			    <tbody>
			    <tr><td>Gross Sales</td><td>" & _fGross & "</td><td class='pct'>—</td></tr>
			    <tr class='indent'><td>Less: Discounts</td><td class='neg'>(" & _fDisc & ")</td><td class='pct'>" & _fDR & "%</td></tr>
			    <tr class='sub'><td>Net Sales (Revenue)</td><td>" & _fNet & "</td><td class='pct'>100.0%</td></tr>
			    <tr class='indent'><td>Less: Cost of Goods Sold</td><td class='neg'>(" & _fCOGS & ")</td><td class='pct'>" & _fCR & "%</td></tr>
			    <tr class='sub'><td>Gross Profit</td><td>" & _fGP & "</td><td class='pct'>" & _fGM & "%</td></tr>
			    <tr class='total'><td>Net Profit</td><td>" & _fNP & "</td><td style='color:rgba(255,255,255,0.5);font-size:12px'>" & _fNM & "%</td></tr>
			    </tbody></table>
			  </div>
			  <div class='prp'>
			    <div class='prbox'>
			      <div class='psec'>Margins</div>
			      <div style='text-align:center'>
			        <svg width='120' height='120' viewBox='0 0 120 120'>
			          <circle cx='60' cy='60' r='48' fill='none' stroke='rgba(0,0,0,0.3)' stroke-width='7'/>
			          <circle cx='60' cy='60' r='48' fill='none' stroke='#00A3E0' stroke-width='7' stroke-dasharray='" & FORMAT(ROUND(_GrossMargin/100*301.6,1),"0.0") & " 301.6' stroke-linecap='round' transform='rotate(-90 60 60)' style='filter:drop-shadow(0 0 4px rgba(0,163,224,0.4))'/>
			          <text x='60' y='56' text-anchor='middle' fill='#fff' font-size='16' font-weight='700' font-family='Segoe UI'>" & _fGM & "%</text>
			          <text x='60' y='72' text-anchor='middle' fill='rgba(255,255,255,0.35)' font-size='7' font-family='Segoe UI' letter-spacing='1.5'>GROSS</text>
			        </svg>
			      </div>
			      <div style='display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px'>
			        <div style='background:rgba(0,0,0,0.2);border-radius:6px;padding:12px;text-align:center'>
			          <div style='font-size:18px;font-weight:700;color:#00A3E0'>" & _fNM & "%</div>
			          <div style='font-size:8px;color:rgba(255,255,255,0.35);text-transform:uppercase;letter-spacing:1px;margin-top:3px'>Net Margin</div>
			        </div>
			        <div style='background:rgba(0,0,0,0.2);border-radius:6px;padding:12px;text-align:center'>
			          <div style='font-size:18px;font-weight:700;color:#fff'>" & _fCR & "%</div>
			          <div style='font-size:8px;color:rgba(255,255,255,0.35);text-transform:uppercase;letter-spacing:1px;margin-top:3px'>COGS Ratio</div>
			        </div>
			      </div>
			    </div>
			    <div class='prbox'>
			      <div class='psec'>Monthly Profit</div>
			      <svg width='100%' viewBox='0 0 240 65' preserveAspectRatio='none'>
			        <polyline points='10," & FORMAT(65-INT(VALUE(_n1)),"0") & " 30," & FORMAT(65-INT(VALUE(_n2)),"0") & " 50," & FORMAT(65-INT(VALUE(_n3)),"0") & " 70," & FORMAT(65-INT(VALUE(_n4)),"0") & " 90," & FORMAT(65-INT(VALUE(_n5)),"0") & " 110," & FORMAT(65-INT(VALUE(_n6)),"0") & " 130," & FORMAT(65-INT(VALUE(_n7)),"0") & " 150," & FORMAT(65-INT(VALUE(_n8)),"0") & " 170," & FORMAT(65-INT(VALUE(_n9)),"0") & " 190," & FORMAT(65-INT(VALUE(_n10)),"0") & " 210," & FORMAT(65-INT(VALUE(_n11)),"0") & " 230," & FORMAT(65-INT(VALUE(_n12)),"0") & "' fill='none' stroke='#00A3E0' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'/>
			        <polyline points='10," & FORMAT(65-INT(VALUE(_n1)),"0") & " 30," & FORMAT(65-INT(VALUE(_n2)),"0") & " 50," & FORMAT(65-INT(VALUE(_n3)),"0") & " 70," & FORMAT(65-INT(VALUE(_n4)),"0") & " 90," & FORMAT(65-INT(VALUE(_n5)),"0") & " 110," & FORMAT(65-INT(VALUE(_n6)),"0") & " 130," & FORMAT(65-INT(VALUE(_n7)),"0") & " 150," & FORMAT(65-INT(VALUE(_n8)),"0") & " 170," & FORMAT(65-INT(VALUE(_n9)),"0") & " 190," & FORMAT(65-INT(VALUE(_n10)),"0") & " 210," & FORMAT(65-INT(VALUE(_n11)),"0") & " 230," & FORMAT(65-INT(VALUE(_n12)),"0") & " 230,65 10,65' fill='url(#psg)' opacity='0.15'/>
			        <defs><linearGradient id='psg' x1='0' y1='0' x2='0' y2='1'><stop offset='0%' stop-color='#00A3E0'/><stop offset='100%' stop-color='transparent'/></linearGradient></defs>
			      </svg>
			    </div>
			  </div>
			</div>
			<div style='background:rgba(0,163,224,0.06);border:1px solid rgba(0,163,224,0.12);border-radius:8px;padding:20px;margin-bottom:24px'>
			  <div class='psec'>Net Margin by Segment</div>
			  <div style='display:grid;grid-template-columns:repeat(5,1fr);gap:12px'>
			    <div style='text-align:center'><div style='font-size:9px;color:rgba(255,255,255,0.4);margin-bottom:6px'>Gov</div><div style='background:rgba(0,0,0,0.3);border-radius:3px;height:60px;position:relative;overflow:hidden'><div style='position:absolute;bottom:0;width:100%;background:#00A3E0;border-radius:3px;animation:pgrow 1.4s ease forwards' style='height:" & _GovM & "%'></div></div><div style='font-size:11px;font-weight:600;color:#00A3E0;margin-top:6px'>" & _GovM & "%</div></div>
			    <div style='text-align:center'><div style='font-size:9px;color:rgba(255,255,255,0.4);margin-bottom:6px'>Mid</div><div style='background:rgba(0,0,0,0.3);border-radius:3px;height:60px;position:relative;overflow:hidden'><div style='position:absolute;bottom:0;width:100%;background:#5B6770;border-radius:3px;animation:pgrow 1.4s ease forwards' style='height:" & _MidM & "%'></div></div><div style='font-size:11px;font-weight:600;color:#7C8A96;margin-top:6px'>" & _MidM & "%</div></div>
			    <div style='text-align:center'><div style='font-size:9px;color:rgba(255,255,255,0.4);margin-bottom:6px'>Ent</div><div style='background:rgba(0,0,0,0.3);border-radius:3px;height:60px;position:relative;overflow:hidden'><div style='position:absolute;bottom:0;width:100%;background:#00A3E0;border-radius:3px;animation:pgrow 1.4s ease forwards' style='height:" & _EntM & "%'></div></div><div style='font-size:11px;font-weight:600;color:#00A3E0;margin-top:6px'>" & _EntM & "%</div></div>
			    <div style='text-align:center'><div style='font-size:9px;color:rgba(255,255,255,0.4);margin-bottom:6px'>SMB</div><div style='background:rgba(0,0,0,0.3);border-radius:3px;height:60px;position:relative;overflow:hidden'><div style='position:absolute;bottom:0;width:100%;background:#5B6770;border-radius:3px;animation:pgrow 1.4s ease forwards' style='height:" & _SBM & "%'></div></div><div style='font-size:11px;font-weight:600;color:#7C8A96;margin-top:6px'>" & _SBM & "%</div></div>
			    <div style='text-align:center'><div style='font-size:9px;color:rgba(255,255,255,0.4);margin-bottom:6px'>Ch.P</div><div style='background:rgba(0,0,0,0.3);border-radius:3px;height:60px;position:relative;overflow:hidden'><div style='position:absolute;bottom:0;width:100%;background:#00A3E0;border-radius:3px;animation:pgrow 1.4s ease forwards' style='height:" & _ChM & "%'></div></div><div style='font-size:11px;font-weight:600;color:#00A3E0;margin-top:6px'>" & _ChM & "%</div></div>
			  </div>
			</div>
			<div class='pbb'>
			  <div class='pbl'>Møller Bil · Financial Report</div>
			  <div class='ptk'>
			    <div class='pti'>" & _RowCount & " records</div>
			    <div class='pti'>Gross <b>" & _fGM & "%</b></div>
			    <div class='pti'>Net <b>" & _fNM & "%</b></div>
			  </div>
			</div>
			</div>"
		displayFolder: HTML
		lineageTag: e5f6a7b8-c9d0-4678-ef01-567890123456

	/// Business segment classification (Government, Midmarket, Enterprise, etc.)
	column Segment
		dataType: string
		displayFolder: Dimensions
		lineageTag: 5397497e-52b5-48dc-ab67-4059321ed0d3
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	/// Country or region where the sale occurred
	column Country
		dataType: string
		displayFolder: Dimensions
		lineageTag: a202514e-0da8-4e4b-a2f7-5a462632ff26
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	/// Product name sold in the transaction
	column Product
		dataType: string
		displayFolder: Dimensions
		lineageTag: 41f6ec18-5505-4b2a-b96c-f889d467161d
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	/// Discount tier applied to the transaction
	column 'Discount Band'
		dataType: string
		displayFolder: Dimensions
		lineageTag: ecc137f7-9c0f-45e7-be56-7b60e04cd072
		summarizeBy: none
		sourceColumn: Discount Band

		annotation SummarizationSetBy = Automatic

	/// Number of units sold in the transaction
	column 'Units Sold'
		dataType: double
		displayFolder: Volume
		lineageTag: c4458863-f188-488f-b1fd-a05cb33fd28c
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Cost to manufacture one unit
	column 'Manufacturing Price'
		dataType: int64
		formatString: 0
		displayFolder: Pricing
		lineageTag: 3da6c4c0-d3ee-4108-8063-16f67ef60e03
		summarizeBy: sum
		sourceColumn: Manufacturing Price

		annotation SummarizationSetBy = Automatic

	/// Unit selling price before discounts
	column 'Sale Price'
		dataType: int64
		formatString: 0
		displayFolder: Pricing
		lineageTag: 7872d975-75a3-4dc5-b47c-1dcac180483d
		summarizeBy: sum
		sourceColumn: Sale Price

		annotation SummarizationSetBy = Automatic

	/// Total revenue before any discounts applied
	column 'Gross Sales'
		dataType: double
		displayFolder: Financials
		lineageTag: 200fa4db-0401-4173-9dca-4d9a4475c118
		summarizeBy: sum
		sourceColumn: Gross Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Total discount amount deducted from gross sales
	column Discounts
		dataType: double
		displayFolder: Financials
		lineageTag: e0168d0a-2d9d-4938-b092-ff2623634e32
		summarizeBy: sum
		sourceColumn: Discounts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Net sales revenue after discounts
	column Sales
		dataType: double
		displayFolder: Financials
		lineageTag: 255c699f-834f-46e6-9da2-76fb4ff1f0d7
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Cost of goods sold
	column COGS
		dataType: double
		displayFolder: Financials
		lineageTag: a84c0b39-d113-4770-ab4c-cb7ce330bf71
		summarizeBy: sum
		sourceColumn: COGS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Net profit after cost of goods sold
	column Profit
		dataType: double
		displayFolder: Financials
		lineageTag: 9bcc22bc-ad37-4011-a6bc-4fcd84ae8a26
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Transaction date when the sale was recorded
	column Date
		dataType: dateTime
		formatString: Long Date
		displayFolder: Time Intelligence
		lineageTag: d8025076-8f92-418d-bb23-34bb005c52d5
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: b303b967-d7b5-46f8-92b7-e342270418f0
			defaultHierarchy: LocalDateTable_8c44b903-78d6-4c61-b341-7c5a8c4310e8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Numeric month (1-12) for sorting
	column 'Month Number'
		dataType: int64
		formatString: 0
		displayFolder: Time Intelligence
		lineageTag: e698d65a-0f4c-40a3-9a85-92b1762825ee
		summarizeBy: sum
		sourceColumn: Month Number

		annotation SummarizationSetBy = Automatic

	/// Month name for display labels
	column 'Month Name'
		dataType: string
		displayFolder: Time Intelligence
		lineageTag: 051f6cf2-b1c7-4375-ba16-b455193830d4
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	/// Calendar year of the transaction
	column Year
		dataType: int64
		formatString: 0
		displayFolder: Time Intelligence
		lineageTag: 52eb4f91-7d06-4450-b877-32764c6cada5
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	partition financials = m
		mode: import
		source =
				let
				 Source = Excel.Workbook(File.Contents("C:\Program Files\WindowsApps\Microsoft.MicrosoftPowerBIDesktop_2.154.956.0_x64__8wekyb3d8bbwe\bin\SampleData\Financial Sample.xlsx"), null, true),
				    financials_Table = Source{[Item="financials",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(financials_Table,{{"Segment", type text}, {"Country", type text}, {"Product", type text}, {"Discount Band", type text}, {"Units Sold", type number}, {"Manufacturing Price", Int64.Type}, {"Sale Price", Int64.Type}, {"Gross Sales", type number}, {"Discounts", type number}, {"Sales", type number}, {"COGS", type number}, {"Profit", type number}, {"Date", type date}, {"Month Number", Int64.Type}, {"Month Name", type text}, {"Year", Int64.Type}})
				in
				 #"Changed Type"

	annotation PBI_ResultType = Table

