table _Documentation
	isHidden
	lineageTag: d4e5f6a7-b8c9-4123-def0-234567890123

	/// Self-documenting model lineage page showing tables, columns, measures, and data flow
	measure 'Overview HTML' =
			VAR _ModelName = "Financial Report"
			VAR _TotalSales = FORMAT(SUM(financials[Sales]), "$#,##0")
			VAR _TotalProfit = FORMAT(SUM(financials[Profit]), "$#,##0")
			VAR _RowCount = FORMAT(COUNTROWS(financials), "#,##0")
			VAR _MinDate = FORMAT(MIN(financials[Date]), "MMM YYYY")
			VAR _MaxDate = FORMAT(MAX(financials[Date]), "MMM YYYY")
			VAR _ProfitMargin = FORMAT(DIVIDE(SUM(financials[Profit]), SUM(financials[Sales]), 0) * 100, "0.0")
			RETURN
			"<div style='font-family:Segoe UI,sans-serif;background:#002855;color:#e0e0e0;padding:20px;font-size:12px;min-height:100%'>"
			& "<h1 style='color:#E4002B;font-size:20px;margin:0 0 4px'>&#x1F4CA; " & _ModelName & " — Model Lineage</h1>"
			& "<div style='color:#888;font-size:11px;margin-bottom:20px'>" & _RowCount & " rows · " & _MinDate & " – " & _MaxDate & "</div>"
			& "<div style='display:grid;grid-template-columns:1fr 1fr;gap:20px'>"
			& "<div style='background:rgba(0,40,85,0.5);border-radius:10px;padding:16px'>"
			& "<h2 style='color:#00A3E0;font-size:13px;margin:0 0 12px;border-bottom:1px solid #333;padding-bottom:6px'>Tables &amp; Columns</h2>"
			& "<div style='margin-bottom:12px'><div style='color:#E4002B;font-size:11px;font-weight:600;margin-bottom:6px'>financials</div>"
			& "<div style='font-size:10px;color:#aaa;line-height:1.8'>"
			& "<span style='background:#002855;border-radius:3px;padding:1px 6px;margin:2px 3px 2px 0;display:inline-block'>Segment</span>"
			& "<span style='background:#002855;border-radius:3px;padding:1px 6px;margin:2px 3px 2px 0;display:inline-block'>Country</span>"
			& "<span style='background:#002855;border-radius:3px;padding:1px 6px;margin:2px 3px 2px 0;display:inline-block'>Product</span>"
			& "<span style='background:#002855;border-radius:3px;padding:1px 6px;margin:2px 3px 2px 0;display:inline-block'>Discount Band</span>"
			& "<span style='background:#002855;border-radius:3px;padding:1px 6px;margin:2px 3px 2px 0;display:inline-block'>Units Sold</span>"
			& "<span style='background:#002855;border-radius:3px;padding:1px 6px;margin:2px 3px 2px 0;display:inline-block'>Manufacturing Price</span>"
			& "<span style='background:#002855;border-radius:3px;padding:1px 6px;margin:2px 3px 2px 0;display:inline-block'>Sale Price</span>"
			& "<span style='background:#002855;border-radius:3px;padding:1px 6px;margin:2px 3px 2px 0;display:inline-block'>Gross Sales</span>"
			& "<span style='background:#002855;border-radius:3px;padding:1px 6px;margin:2px 3px 2px 0;display:inline-block'>Discounts</span>"
			& "<span style='background:#002855;border-radius:3px;padding:1px 6px;margin:2px 3px 2px 0;display:inline-block'>Sales</span>"
			& "<span style='background:#002855;border-radius:3px;padding:1px 6px;margin:2px 3px 2px 0;display:inline-block'>COGS</span>"
			& "<span style='background:#002855;border-radius:3px;padding:1px 6px;margin:2px 3px 2px 0;display:inline-block'>Profit</span>"
			& "<span style='background:#002855;border-radius:3px;padding:1px 6px;margin:2px 3px 2px 0;display:inline-block'>Date</span>"
			& "<span style='background:#002855;border-radius:3px;padding:1px 6px;margin:2px 3px 2px 0;display:inline-block'>Month Number</span>"
			& "<span style='background:#002855;border-radius:3px;padding:1px 6px;margin:2px 3px 2px 0;display:inline-block'>Month Name</span>"
			& "<span style='background:#002855;border-radius:3px;padding:1px 6px;margin:2px 3px 2px 0;display:inline-block'>Year</span>"
			& "</div></div>"
			& "<div style='margin-bottom:12px'><div style='color:#E4002B;font-size:11px;font-weight:600;margin-bottom:6px'>_Documentation (hidden)</div>"
			& "<div style='font-size:10px;color:#888'>Calculated table for lineage measure</div></div>"
			& "</div>"
			& "<div style='background:rgba(0,40,85,0.5);border-radius:10px;padding:16px'>"
			& "<h2 style='color:#00A3E0;font-size:13px;margin:0 0 12px;border-bottom:1px solid #333;padding-bottom:6px'>Measures &amp; Pages</h2>"
			& "<div style='font-size:10px;line-height:2'>"
			& "<div style='margin-bottom:8px'><span style='color:#00843D;font-weight:600'>Overview_HTML</span><br/><span style='color:#888'>&#x2192; Page: Financial Overview</span></div>"
			& "<div style='margin-bottom:8px'><span style='color:#00843D;font-weight:600'>Sales_By_Segment_HTML</span><br/><span style='color:#888'>&#x2192; Page: Sales Analysis</span></div>"
			& "<div style='margin-bottom:8px'><span style='color:#00843D;font-weight:600'>Profit_By_Country_HTML</span><br/><span style='color:#888'>&#x2192; Page: Profit Analysis</span></div>"
			& "<div style='margin-bottom:8px'><span style='color:#00843D;font-weight:600'>Overview HTML</span><br/><span style='color:#888'>&#x2192; Page: _Overview (hidden)</span></div>"
			& "</div>"
			& "<h2 style='color:#00A3E0;font-size:13px;margin:16px 0 12px;border-bottom:1px solid #333;padding-bottom:6px'>Key Metrics</h2>"
			& "<div style='display:grid;grid-template-columns:1fr 1fr;gap:8px'>"
			& "<div style='background:rgba(0,26,58,0.6);border-radius:6px;padding:10px;text-align:center'><div style='font-size:14px;font-weight:700;color:#00A3E0'>" & _TotalSales & "</div><div style='font-size:8px;color:#888;margin-top:2px'>TOTAL SALES</div></div>"
			& "<div style='background:rgba(0,26,58,0.6);border-radius:6px;padding:10px;text-align:center'><div style='font-size:14px;font-weight:700;color:#00843D'>" & _TotalProfit & "</div><div style='font-size:8px;color:#888;margin-top:2px'>TOTAL PROFIT</div></div>"
			& "<div style='background:rgba(0,26,58,0.6);border-radius:6px;padding:10px;text-align:center'><div style='font-size:14px;font-weight:700;color:#FF6900'>" & _ProfitMargin & "%</div><div style='font-size:8px;color:#888;margin-top:2px'>MARGIN</div></div>"
			& "<div style='background:rgba(0,26,58,0.6);border-radius:6px;padding:10px;text-align:center'><div style='font-size:14px;font-weight:700;color:#e0e0e0'>" & _RowCount & "</div><div style='font-size:8px;color:#888;margin-top:2px'>ROWS</div></div>"
			& "</div></div></div>"
			& "<div style='margin-top:16px;padding-top:10px;border-top:1px solid #333;color:#555;font-size:9px;display:flex;justify-content:space-between'><span>Source: Excel Financial Sample</span><span>PBIP · HTML Content Visual</span></div>"
			& "</div>"
		displayFolder: Documentation
		lineageTag: e5f6a7b8-c9d0-4234-ef01-345678901234

	column _dummy
		lineageTag: f6a7b8c9-d0e1-4345-f012-456789012345
		isNameInferred
		sourceColumn: [_dummy]

	partition _Documentation-Partition = calculated
		mode: import
		source = ROW("_dummy", 1)

